[package]
name = "bee-api"
version = "0.1.0-alpha"
authors = ["IOTA Stiftung"]
edition = "2018"
description = ""
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = ["iota", "tangle", "bee", "framework", "api"]

[dependencies]
bee-tangle = { path = "../bee-tangle" }
bee-transaction = { path = "../bee-transaction" }

bee-ternary = { git = "https://github.com/iotaledger/bee.git" }
log = "0.4.8"
serde = { version = "1.0.111", features = ["derive"] }
serde_json = "1.0.53"
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2.3"