[package]
name = "bee-api"
version = "0.1.0-alpha"
authors = ["IOTA Stiftung"]
edition = "2018"
description = ""
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = ["iota", "tangle", "bee", "framework", "api"]
homepage = "https://www.iota.org"

[dependencies]
bee-crypto = { path = "../bee-crypto" }
bee-protocol = { path = "../bee-protocol" }
bee-transaction = { path = "../bee-transaction" }
bee-tangle = { path = "../bee-tangle" }

bee-ternary = { git = "https://github.com/iotaledger/bee.git" }
log = "0.4.8"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.55"
tokio = { version = "0.2.21", features = ["macros"] }
warp = "0.2.3"