[package]
name = "ternary"
version = "0.1.0"
authors = ["Bee developers"]
edition = "2018"

[dependencies]
common = { path = "../bee-common" }

#lazy_static = "1.4.0"
#failure = "0.1.6"

# ONLY TEMPORARY
iota-conversion = { path = "../iota-conversion" }
