[package]
name = "network"
version = "0.1.0"
authors = ["Bee developers"]
edition = "2018"

[dependencies]
bundle = { path = "../bee-bundle" }
common = { path = "../bee-common" }

tokio = { version = "0.2.9", features = ["tcp"] }
