[package]
name = "bee-network"
version = "0.1.0"
authors = ["Bee developers"]
edition = "2018"

[dependencies]
bee-bundle = { path = "../bee-bundle" }
bee-common = { path = "../bee-common" }

async-std = "1.5.0"
async-trait = "0.1.24"
blake2 = "0.8.1"
futures = "0.3.1"
hex = "0.4.0"
log = "0.4.8"
