[package]
name = "network"
version = "0.1.0"
authors = ["Bee developers"]
edition = "2018"

[dependencies]
bundle = { path = "../bee-bundle" }
common = { path = "../bee-common" }
futures = "0.3.1"
async-std = "1.4.0"
blake2 = "0.8.1"
hex = "0.4.0"