[package]
name = "main"
version = "0.1.0"
authors = ["Bee developers"]
edition = "2018"

[dependencies]
bundle = { path = "../bee-bundle" }
common = { path = "../bee-common" }
network = { path = "../bee-network" }

async-std = "1.4.0"
futures = "0.3.1"
serde = "1.0.104"
serde_json = "1.0.45"
