[package]
name = "main"
version = "0.1.0"
authors = ["Bee developers"]
edition = "2018"

[dependencies]
network = { path = "../bee-network" }
common = { path = "../bee-common" }
bundle = { path = "../bee-bundle" }
