[package]
name = "bee-main"
version = "0.1.0"
authors = ["/alex/ <Al3k5@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
