[package]
name = "bee-message"
version = "0.1.0-alpha"
authors = ["IOTA Stiftung"]
edition = "2018"
description = ""
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = ["iota", "tangle", "bee", "framework", "message"]
homepage = "https://www.iota.org"

[dependencies]
bee-common-ext = { path = "../bee-common-ext" }
bee-ternary = { git = "https://github.com/iotaledger/bee.git", branch = "dev", features = ["serde1"] }

bech32 = "0.7"
bytemuck = "1.2"
hex = "0.4"
serde = "1.0"
thiserror = "1.0"
