// Copyright 2020 IOTA Stiftung
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and limitations under the License.

#[cfg(test)]
mod tests {
    use bee_crypto::ternary::{Kerl, Sponge};
    use bee_ternary::{T1B1Buf, T3B1Buf, TritBuf, TryteBuf};

    fn kerl_generic_digest(input: &str, output: &str) {
        let mut kerl = Kerl::new();

        let input_trit_buf = TryteBuf::try_from_str(input).unwrap().as_trits().encode::<T1B1Buf>();
        let expected_hash = TryteBuf::try_from_str(output).unwrap();
        let calculated_hash = kerl.digest(input_trit_buf.as_slice()).unwrap().encode::<T3B1Buf>();

        assert_eq!(calculated_hash.as_slice(), expected_hash.as_trits());
    }

    fn kerl_generic_digest_into(input: &str, output: &str) {
        let mut kerl = Kerl::new();

        let input_trit_buf = TryteBuf::try_from_str(input).unwrap().as_trits().encode::<T1B1Buf>();
        let expected_hash = TryteBuf::try_from_str(output).unwrap();

        let output_len = expected_hash.as_trits().len();
        let mut calculated_hash = TritBuf::<T1B1Buf>::zeros(output_len);

        kerl.digest_into(input_trit_buf.as_slice(), &mut calculated_hash.as_slice_mut())
            .unwrap();

        let calculated_hash = calculated_hash.encode::<T3B1Buf>();

        assert_eq!(calculated_hash.as_slice(), expected_hash.as_trits());
    }

    #[test]
    fn kerl_input_243_output_243() {
        let tests = [
            (
                "HHPELNTNJIOKLYDUW9NDULWPHCWFRPTDIUWLYUHQWWJVPAKKGKOAZFJPQJBLNDPALCVXGJLRBFSHATF9C",
                "DMJWZTDJTASXZTHZFXFZXWMNFHRTKWFUPCQJXEBJCLRZOM9LPVJSTCLFLTQTDGMLVUHOVJHBBUYFD9AXX",
            ),
            (
                "QAUGQZQKRAW9GKEFIBUD9BMJQOABXBTFELCT9GVSZCPTZOSFBSHPQRWJLLWURPXKNAOWCSVWUBNDSWMPW",
                "HOVOHFEPCIGTOFEAZVXAHQRFFRTPQEEKANKFKIHUKSGRICVADWDMBINDYKRCCIWBEOPXXIKMLNSOHEAQZ",
            ),
            (
                "MWBLYBSRKEKLDHUSRDSDYZRNV9DDCPN9KENGXIYTLDWPJPKBHQBOALSDH9LEJVACJAKJYPCFTJEROARRW",
                "KXBKXQUZBYZFSYSPDPCNILVUSXOEHQWWWFKZPFCQ9ABGIIQBNLSWLPIMV9LYNQDDYUS9L9GNUIYKYAGVZ",
            ),
            (
                "GYOMKVTSNHVJNCNFBBAH9AAMXLPLLLROQY99QN9DLSJUHDPBLCFFAIQXZA9BKMBJCYSFHFPXAHDWZFEIZ",
                "OXJCNFHUNAHWDLKKPELTBFUCVW9KLXKOGWERKTJXQMXTKFKNWNNXYD9DMJJABSEIONOSJTTEVKVDQEWTW",
            ),
            (
                "EMIDYNHBWMBCXVDEFOFWINXTERALUKYYPPHKP9JJFGJEIUY9MUDVNFZHMMWZUYUSWAIOWEVTHNWMHANBH",
                "EJEAOOZYSAWFPZQESYDHZCGYNSTWXUMVJOVDWUNZJXDGWCLUFGIMZRMGCAZGKNPLBRLGUNYWKLJTYEAQX",
            ),
            (
                "FMMZTLNOZUWJUMLRUMZNQOZG9QQNWFHJBIKAMNMKTNKHZVKQALHPKUXHZSSRLKJFPIHCFZVZFEVOMBDUF",
                "USXHTPUJJXFQTWPDTV9URTSM9VBVFMBIQQ9VBKWGZRLDIZKRNAD9PWZZQMTFAZAK9ZMLGTMEBOOJB9XBA",
            ),
            (
                "CLKAPNTLUMITSDWRLDHYHEOURFJMKUDQXZXAMNGTJYOOKRRVYKPIPOVPNYWYITITLSJAXARZTQYDDDSZP",
                "UJAKNHBYKZAUQ9XCROPDRNIZWBMINFGOEAYTKASVLDOSFMCDZZLGOUQ9I9OGQLKTOVBMQZELFVIKIOBB9",
            ),
            (
                "COD9QLD9QGBCFVVDIETJXUPACVAKNKRPFIIXNOXFSJRKGDOGPIQMVDWKOIRODYFMUAO9HLKDGTEMHOSQQ",
                "GHJXHUAPEMWZTQDFLERAODMTOEMCYDXVVKDHYIGCMTRRDXVOXMSWBGSBZCZFKWMQNPZDYZYDBNZTVESTC",
            ),
            (
                "FPZELSWBZPBZCGVAZYROALBTEVTUBVPDWRZWDKAWJVWPADCPWXCFBEREADV9AOZSM9VQ9GGRZOSARZNHG",
                "DCGHRTZEKHICXRCTCXPLEQFDAOCKFVTDOBMXVYWZJLAPQUZCIPJF9BGCJF9CXPBVAAETDUILX9DTKWZYX",
            ),
            (
                "TGKMNVKKGKMLIEMALEANLGYQMXTSVSZAO9YJRSLZJIXVSPLYZEZUOSIEWYJXTOEIUDGRVSPEDPKIYLBPF",
                "FLXPXOTTDPTMVZU9GJOXEAVRLHMEPRUXCITMQNNPZXPVQMUPDCJGDESLFGFGOBUTUJATIPG9NPJSASRHW",
            ),
            (
                "A9QHKAZPRUVLMTDSXYQYAIEFICA9EAEKLUVHEPHIUPJZLSBXLEGHXNQDIUDDSLAQCRINVUMVJMZPGHPTN",
                "LLXWPVEIQOK9WQUPCIGODVMJLSKMZPVDBUQKUTUNMVWMMOJQZGROEXTWZTRLPBBPFWHFJ9D9KWQLUADLA",
            ),
            (
                "GSSONEJY9VXSFNTYOBXHCHOB9EODIOTBXJMZMXOVHZQB9AEOZIJUM9PTYGYNGESR9ZSIKDJ9KEWIB9FAY",
                "SIQINLOFCHVANBUUOMYZUKEAVH9AVYAICXNFAGZGWQLLQD9HLBLSLVYESIAFJYJVYRVYGMYXERJZDDGDB",
            ),
            (
                "VBTTOJXZQLRJUNDXBY99ZOHVWZIUSTCSJATNCMAIOSQKDNBDVLVWEHQEHPBKCDPCXMKEXEMYHMDYKWNNB",
                "HLPRUENCJMDVQQTTWQ9LKHETLXALMGFRSCEIB9CMI9XLZAHFPTHXW9PWRCPAKZLGEJZHPTPEMVR9KFLPX",
            ),
            (
                "ILJLMZNJCJMHBWUOPVADFTBZZIWVGA9MCUGJVVXZKQIHRBQVLTXFCZL9EHHOEIRED9CXFMTTKOWPDDALJ",
                "AQSVEXFZVKQOBBMIUMRJV9HPTZJZETGGILFXNRYPWAWBZHSUDEBLYWMIAPVKMYALCCIAKHCCKHQHGHTCD",
            ),
            (
                "OOVPLZATVDZXGNENSFKKPQTPIQJTCPIOSGEJDBIKCGKK9LHED9GWYZXXUO9DAESQKREANXAKKQBYPPUEZ",
                "JTFVFGCAQNKYVHRCGABUP9GNDNYIRGZQMWHMJSEABAILZPMVKXVQ9GIEPDZDKB9JBDLBDBMQWACNRDPYA",
            ),
            (
                "MJEVWBFMD9OZ9QIGYEF9CEQFSZHYPPZKNJ9KOBKCVWR9OJ9IQFVAZYLXO9BNPSTQBCNESHZHJCMPFSLSQ",
                "YVJNGOIBVYVNMKN9SYPFMPJWJUCXZHPMRBICZQGYWKRLGICNAQZUHTGRROEVHVNML9SAZDAX99QRGMKNA",
            ),
            (
                "RQXJUDVHGN9YUUDEDHDXCHAVUIVZHLQTZIJVLGNAFIIDYGVX9BOCMIDOKMPBZCNCGTYKRLTDSFYVLZOOD",
                "TELHYNCIHGTKCRC9IQDWBLSGPGQPRZCSVRYIPZJ9KXILOIDIHXRBSTMOJZRRRLSNHQGEH9AHROOZYEEMC",
            ),
            (
                "FKKKPTUKJOQXVOQSYBZLPWXPSB9IRTKUPM9OWDSLHYDKJUHCCEWAXRJXXZVGMYWSNTVNJCBSJLDFGYQRX",
                "ADJCUWPLCAGLSTPSOHVQCBCAGJHPWRXFWYNAYLADTHNRECVQDXM9OYGZWBARIEJTBISFKRTMBBXXLXDOW",
            ),
            (
                "AU9AW9RRLZQGMXDYIYADHAGSNLDQEEGSM9IOBFVEKTDYSVXEUJATJJFYAFA9KGL9JHKJOMSHTP9YYZBKT",
                "FCYDZDQFTFLQ9EBSFACTWTVGKCUBGJZPVDVPISGGJHHMNOBXXFATZFX9GNHUNGLILYQ9JPSBHBWWCNGUX",
            ),
            (
                "J9HER9GGWHKHTLPHYUXWEKAIKMXHPVWXQSBYMMDEFUSAYZDHKUBHQRYWICOSQRASXHEFDECMCHJHJKIVK",
                "NATACRWZMFAPEKI9GNZCRXZFJXCZHVZQOFHQTXKMNQHEQOYMPVQWVGELKYIZVLNCIMRLDH9QKRUJFJYTX",
            ),
        ];
        for test in tests.iter() {
            kerl_generic_digest(test.0, test.1);
        }
    }

    #[test]
    fn kerl_input_243_output_486() {
        let tests = [
            (
                "9MIDYNHBWMBCXVDEFOFWINXTERALUKYYPPHKP9JJFGJEIUY9MUDVNFZHMMWZUYUSWAIOWEVTHNWMHANBH",
                "G9JYBOMPUXHYHKSNRNMMSSZCSHOFYOYNZRSZMAAYWDYEIMVVOGKPJBVBM9TDPULSFUNMTVXRKFIDOHUXXVYDLFSZYZTWQYTE9SPYYWYTXJYQ9IFGYOLZXWZBKWZN9QOOTBQMWMUBLEWUEEASRHRTNIQWJQNDWRYLCA"
            ),
            (
                "CXOXVFNGUPEUZESXHFBVHBNAAJNONJBPVBNJKP9QXWYGEVXOCUULVQKSSMLMJJUPVBYZ9FHMZRZYEPKSZ",
                "RSCSUVIEVAIJDMERX9ESPIKIJIGYRRCPQPJUSCEYWQQJFWRHMAUPKWN9FATEWDOGEPGP9VZAZVOLFDVVDCJHQTXFNLLHQXGXCCDXCNPKDYXXUTHBCRVRJHRVQAYCLQCSNVRKSN9RXM9IFWLQXB9ZXTEQTIRIKTXPNY"
            ),
            (
                "KFHRWRNKPBIXR9DQC9NXEZDWJHDIID9DFJSNMIQ9PM9PSBMHPBNYKGATCYADJFVGEDKLQEMJNVWVIV9BJ",
                "VTGUEYQYEEOMVNUIKHRCD9NJUMQRQVGDARJBETPULYKXQGZKZDNE9ZEGPYOJXNYNTYWOYLUP9GPX9UNJC9BAZFGBOLISAXTPVPD9WWAHQUWPVJOCOLIDINAC9AKYVUCLUWIECSYRZRRBVLAUMDOCPZASDUWZZNJKMD"
            ),
            (
                "AEFKWYAMFHKZQGH9MEGMVBGQKV9FNVFLXSWDBDMQMO9IEQGQKZDWBUUHPNVSIQ9HCMATTN9OSTM9YR9AC",
                "SFGULJLBXGCJRJBVYURBLURFINUOHVILXIGVRNXFPJWSBHYLRCICOYEMGKDMTTSEAFIM9USGCRULVUXWCLIPRSJBWAYOVUOURQUVLKLCNSPTPLJHEVUEPUKXPMJOPVSBSUKIWZFWQSQMXDU9ABFGT9WTZGODUMJGJZ"
            ),
            (
                "SWKSDPAMOI9LLXRQYIFDYETNUSHGCHUVQUMFLV9FXFEFEJVPDIMD9NHIYXIJUWENKHFROQBZA9UPUU9ON",
                "OUIURXMTDOCUAMG9RGKBGOLZKANHFKSQUKPDYGCNNFHFOJDHAVZEIFXOWMMTOMPFQCGLYFSCVDDWEEUABJPEWAKKIJOEXDQCU9ZEZMQRSWFWPLQROVCQYKHMAZMQVVE9DOMLSQEVFW9EUXEUGSGWKMDWHCDSGWPXQX"
            ),
            (
                "KVSAXCWHCVD9NDCGQPJNROGNATNNMGLMODYPEGBCRJJAYFIVLP9ITLDGARAKBQZLUSJZRO9SKWCFMRSWD",
                "CGPMKTXWEYYZOE9MMHGH9GGTXJBWKKBOXJETVKTQTWPOAOZRJLHYWGBWFLZSHUPMMTZMMRPWAJHGPDWJYVJELBIKC9WJJGGSXESPPGWLAH9MYUAGAGIOGNWPXUGEMWNCMCYNHQCMFYHQ9T9XYFRFTUPKMEPABCFTRD"
            ),
            (
                "QJRMWWBQHCLKBUXZLOREVDQRYEQZNDOSIVEQGBBPUMACRGERUBBZTCOFSYUYVLXFPJBO9CUXIQPIGPISO",
                "HMXKCCATN9NTTGMADKIYKW9DM9HPQCBIMT9IJNDZJAZHYTJRPCTSGYDLXHZLIFRTOVOBBLWITPMALOJIWSDZBGHSKGSDJZBLSEFVTK9YLDNS9QDYEIODSXRVXUWUCVSBAIAUWNIYMGXJNKRUMCWHRECTRQQWW9MOWW"
            ),
            (
                "UYWDLKEQIBHL9CDOWRVZFAGPUZKGTYWDFIUBTWRAVXINAGKAQUMVSZMEVGAU9SZNDLRGPDK9MZ99KYSLL",
                "SJTKBFYODYYIJRSGFGLTARGGKJDTTSADSXRGPUXSVACHBIDEUMWUCOECFLHOGXEAKAXFT9ERRKCAZUUVXDTGFYERFTTKHWVAMYFBLAAAKHUOKKFMKQOTSIURUXFOYJNDWUAIYXPZT9NRFDWEZ99OFPVDPCPTONIXWB"
            ),
            (
                "TUNIMRFTEC9EPWYMEMJXGPU9BBHW9PGEJOYEYIWVIARERV9YS9KZJOKMBIBFAKKIIUWGRR9RQMHFRXPVC",
                "ZCGTDRVLOKEJAMVJRBUSDELVWECRNJIOOVEE9XMFQDY9RCIBAWHPW9VZKBVGWWTXYTRZLSNBGOC9PYHIC9VCW9ZFQEDHAYPZWKAPYUQQJAWHTAZXQTKVKFVRXSVAPQ9KUIPFOZWQEAABAMOCUXILJFTHQBMZCHXYNA"
            ),
            (
                "WCCAZJGBCAATESCXQVXZJTDFIYJDAWXFKJ9DPKQGHLQLKKR9RNGIAQVSNYAHIYMX9QUBSAMHVUVWXDGXA",
                "RBBBT9KWEKBDEFGS9XGFJWVLM9PXGCIEQRUSRLSBM9VIAGLFWUYWAJNNHVCRVXSPFWAVBFRMCUZKXPQKWVHHVRXUMZVFGVBCVEGBBIISOLIBYEKBNZVLHCIJMAYCZZ9XKZZJORJIUPUST9MGPSMQZTYBNESTDXBIMC"
            ),
        ];

        for test in tests.iter() {
            kerl_generic_digest_into(test.0, test.1);
        }
    }

    #[test]
    fn kerl_input_243_output_6561() {
        let tests = [
            (
                "PQ9YDLLUQYNUKPCPGHYHQKJNBOOOSEXXGFWTEQQTV9MLPMPGRDIKYWWEQZPICNPCZIIINTULV9UXXYUFT",
                "YZ9KARNMPCZYBJFVPEXYUPWIBTIVGI9ZYEYAIUYRVYHF9DFTNRBHKSLIOSNDDMNUVYOAXKJCHUWOXIPSWUOQGGYEJB9PTDARNIIKPDKHKUHNJLM9FBRYRUMHIDKBSSEBELLBZVXJVKNMBCSHOHZXMBXMSAVQTSJBZWR9FRJKKRSQML9GJYSFSAONDQBY9YKIWUKADS9WBSNVSHYYNTYWQUWPXHEOLUPTN9MG9QCODWPWHCTALJWZEYRSBIIUMFMHXPVKCQAFSSQECNYLHEFWDITSHFUO9ZPNIRYSWFOOGKL9BFBZEWSXFGAHSOVDUQHCFYZCXXAWTYLZ9HXDLRDKNHDCGBXUHGSAXIBPIGQEN9DEFKH99RZSRFNEHTMZCPKVQVVXLBAZEHLXTUWYYNC9YDHIGANXVGIZPJGCZHN9DBJFFVMCPUQUBPTSDLBAUEQVGVAJTHEMVSWAFMAMGVSIESERMM9NYNVZLJHDQCZADFUOICJOOZITWZPZSWWUZCMWBOGLXJJWMYKIYFGVHGPLHVPFKVFPNL9OWJPYSAJVJW99VPVLQPXGVBAEKXLSF9CN9XKHD9MRUQS9KKDVOZLABWKJTGVEOMCUPNRUYRRVYGYZNFCTHXFAPRZGFPCUQLEWET9HRDYWPMXIMUMVGOZWQZHRBIGUEVWZVZZKCFMSKLXYEQYZQDEESHIMAELTUFUHCLOZQGIBKKCYIEONDYZDXWSPXGPZFFRIVJAICURQPZCNNNK9HIWBRNLWODSGGBUQXEMXLZTXHHEUJNKTJGSWYB9VRIXFYPIUP9DEBJXMQD9BFCJIATHMAFIQGDCPSVIXHZJEOBYWPXCXCEMXYNHFMCCFEOSMQZUQTKP9GXIEJHBTRNSCNZNUKSP9NECXKOOOJUFEQLMPCIZDVSFGTDBHWDJUXZAH9EEUBXKVHSGYZFYHFWKDPNDDHFFYQKQZNMQVNNOIJLFGAJO9UMIWJNDCANUWJVEOMOFMGBBBWYIRHZMVCNPFJQPJUGGORHNKVLYCCKDYJVBOR9NUMJASZZISEYOXR9YEAFPATWVBGHAMHDIUKJHEAAKZRFVTHCOQXGFVCGSUSEIEVHMCJTWTZOFHHOOBGXANIONX9ETKLGIZTYKYFBUEMWOIBTPHTEDTYSXWIWEQTTDQDVJCSTBFFCOQGOAVGMSZHASDDBXJHLAGWRGAEVZKFAPCFMBEEGSFKLDHPRSQMBBKRHVRGGFS9KWUPZFUWPOWLXBNDNUBDVKP9KZSOQQPRVSOWAWDMSRFBLJZOIYELEAPRRBYRJA9IBHCEG9SPFTKSNUMLAJWSCWUKDLXVCLKVPWZWCEDGXFZLNGM9BDKRFFUXIQNOCRGBZOGYCKORQWQEKOSXPK9QQTWNCFUFTTQCTKZRXKRIKOGRI9RYOFUBBX9OLFTTSURKSEDWBTBYMGMDHYJLZDFOKCDLTFELOLAYDCHPK9RXYKXRDJOSWVJELSHFD9VYVWDHAUTGWZQP9NCRTIRNMWZY9FGNBQNEFBSYBLPAQSXQXUYNRRTPOYRZQUHLYVCWJPILNMVEYZCPJYLVRSCRFTYUNNCVRYCDQREQHSIHFON9CBTOURVUTTMWGGAEZAFYNHYJNI9JT9LHERHBXWBJGCKUCFDETS9MSEEZPQMSSMBG9NFYCVVGQHQCD9SLONUWRSPTMVQSUQBJMBOFUYQEUQQZZRHTSQZLTTLXYUQNNOPRTYGTAEORCSNEHFJVSMCXRETKCZWHQUDUBET9QKMRZNIFS9WWGYLWOIBIMQRCZHKHUCXLVWCLOBVZJSXZRWNZVYBYQTMMGBUYFBW9HGRWBVAYJUEPSQKFEMPMCOWJDRIYOKOGUFKBKOXIADDXNEQKKGAMLIWKNIFIWEXJTGUFZNOLCHGYOZQDSOYYLZMJWXPLTAXUUAVUOPETRVJSCQYHRJMFANEKIMCIKCVBRKDJ9VRKJJALBTACU9LVRTN9AFZNERMLXZVVHVTTYBMGADFYHEQZLNJLSZAAJFGHMXXBBKAKYEGXZDVNEGDWFTRDJCUIGONKHBAODRP9ZUMWJHHGOLVKES9LDGWZCGFDEFUVKRUBW9UGSCJNXQN9BUUKIQVMCWF9PKRF9AKATGIZIOXFFKSGCXRSJMTEXENJPVDHYUAMQUQABGLSUFWPPWNTEPPSWEUGSBNZJYNTBBFUSY"
            ),
            (
                "OLTQRBZYZLID9RKWBN9LQVFNITBGADSKAIJZ9NZVDAQVHHQMTICZRZKH9FKDMLICPPIT9BRVW9FBQPORK",
                "XRWLC9PXAJORZZSWHXKHPPCIMACANEBAFCOGGWWZKFBGAEZUYKYJSNGBYJUFIRYLYLMLUBLJZC9TYOBECTJUDYUBCBBAKIWOHSZL9GMAMMGXPTNXVMUEVDHFSGFOTTWDPJB9ZXPBPVBZXKMU9BEDDLLSYDHGVQSOYBFSNJPJDZENGPUQHCPAERYLIXOLVWTLM9PXWEG9KNTFLRRPYBSBNVFZCV9HRGCIGFWJSOLFLTVHWZPHRQDUT9LEXUNMNIMNNJWFJEOFMDNHZDIYXDDZFNCORVTZY9MVPBBN9RKTYUJRTUE9UBIZMUZBFPBOZHOZTTXAETUPPSUS9SNSP9MANRFEPGRLAAZAXHFHZOVKDBIJBFSLJZMUUJYKBWLYK9KATYUCPMVKKWAYYPAXQFMV9JD9WNJHXJHMUWEXMLYCMYRFRWTMKTCVPYKHLGQOFROQUOFCBYGIDEXUNSRQE9RKDAIZVHBHRRYLBI9JJAKMNJAOPKJOSNBMNYFLYTZV9SJTNKNXSDEAYYXQNMRIPJQLYDYZWKGVPFPGIBURSOOZOFBTUDAGOMDZNCCDGOXTMIFIVNUQYMRUJPDLAGEVCYLYVFGHCESLYPQRMJVBTLYHUJVBAPRZGDOOYQYLPVGQMQQTSUFNWYABQODEKU9PENXHHQMXF9LMWVSIH9DMNNIOCRVQUTZLHHKUXLQGZUJNVGRQQCCAOJNGUHXQMNXZSFY9YXJQXHHMMZIFTTFNDDKXQCCMREYSYENSLMQTJGXJFMVFRVYIHHJJWACYVLOUWCJFPEKABVAUJ9EDPYIOVMOAXXLZRQBVRDGJKHDDLEWYMKNVDOOKXEVYAHKYBOCOF9G9NWSUPKSIVQAJZZXPHHBVJ9SZGFPTKBZEYLBQBRCZXFFUFCU9QPFAJALQ9VDGQZFSNZPJMTAU9LQBMMIXYRWSMMUJTVFAPV9ANUVUBPPEJVDUCNJ9VMMZVGQWGPHZTGGXYMTSLAQNHBZBPGDOTGPWBTQUAAPAWZHZPOAECHEAVUVELDUGYJDOYILYOQ9CLSLMCADJAM9C9WGEZEAEOIVSDN9JVUCCRDFGUBBUM99EIKXOGH9UZIAMDQJNBKMWURXMFP9YEVCTGZQMKGPYXQYWIVTFJZJNYAXZVES9PWKLVRXCJELAUCVXPBRWKADPFYIJLQBZAKTCVAWXOJLEJMQLH9DQAXZOIKCAQTIVBELTCNXSHHIYMUKPDUYXDQSVQGQJFBAUMPTHECHRB9PEEBSLTJPDGTBPSZQSIGABGILKUAOQVDOVRP99VPSQDGGDSDOHNXYPHIPFVWINO9IVPHFMUIODXDJCVYOEOMSCMWXARSVXMVJJYRXZJGVYQTDIRIMWZRTXBFMLLIJHCJWSNVWSZBIFIEEWKDEMKGDZHXSPQE9YVVQUFMHGZBMSHEFUYTYVINYW9QFVXDQSXBASAELCMZIPUJYFGBEFSFWDLTOZIRJQMEZZLQAQVVWXNFEUEGLNVNVEBHXXEQTNUCX9DGQMEWSWCA9GELZCWNWZWCQHOWJR9IY9CITG9DKSXTGJZ9PQHKFQDXCWERAHKVDDOAPYXGRVDSN9BCDJFVIMJZTLOGS9ERSDEYBTLRQPCNLPXCDZTK9GPFLMIXZOKJFVDJKFAEFOLTABRJWMYCWYBXHERYYJQJXDPDSZJWIOPHZVJZBDWXNIJZJNN9RIOPYRWQILGQYKAIBIYWVJJVSLVOHPOOP9CFETJMSBUDCQSLJV9JINPEIXJAORFGE9CP9TSYCUUOXWAXFKLGMP9XBVFKLHABVCB9ZIQPALFGIPOROFSCYAVWOZCYANNENXZFELMYYQOAUPZIOTHQDCSTQQMMZEDATFTDMPLVZ9BFJRMPKPJPTGAEUVSAXELI9XHXEEAHQGVUEGPPGAZTAIWBMSIKTSIZVUQJDQBGAAU9UTFTCZSCEOW9VCJTHJXABHLUEMKTWHBVGBZJHANXYJQQPZRXLUB9UBPOERCGELJCDVPRAGPNIKTWAJONZWZJPILSREVXNLWLPJRPBPCEFDORMMTWKFOSQKQGXRADDOJSHVNIAEVRKAYEYTKBHEDLJCSUQHAXGYKXPEBTIHGOJBKOCKRWVOTMJMDTFJDVD9UPTAYBXHJXOGMYEGWFPPEVMRTS9EEXRASDTHDPGKONNTLIPOGIHRI9FHPDFJAQJQSZX"
            ),
            (
                "GYWHCDMUIBOFMJTHRDQJQHEXPWNNLMBRMNP9WWQQ9FJQAEWWFDZPRQDNMIYXYPDFRSJVATBMGOPYQXZL9",
                "UTVYWUXRYLOU9HCZALSEH9N9MLYNVNAHGYHQMQOTRBN9GUYNAT9IUGRKHOCUSGUEJLPPI9ZAQTAPYGMEWUWTXVDBGSXKXDKGOQXCAJKMPCDUGJXVTMDBSZTIXJHAPPYYZV9COFLKLVQZSPM9RFWZZKXRTNYHKRVOEDZDFABCGMYGERKKC9QLEJVWEVTNBVLYCFQYMLVCEYFWZGCQKLZARUITWKKAPLZHDICKNEXGJWLGBBHBTLWMZLBXKKO9DFSEMJTOWYHDLO9TSMAPUQUTKXPDYPDFMMLZDSPP9VEJUARDQOZCWZMONYMXUPSIDRTRADTXSHEAC99IIWIQBOPATNUI9QCAMAUDJDAXAPJLJ9BSDLVCGTLZM9BMCNOJYFUBLQNSAKKSOHQMDAOHHVSQWHFZWRYZ9GLEGGDDILKZQFELKLYGZUISBSLJFDJNVYNXIFI9ZWLNLNDZXYOV9MCLVKZZYMTNRKGDGZYICYADMZFOEILZPHGPIFCWNATHNKS9KJXVPNBJKPCZAQ9BTHQIVUNQNVMBJDXBZGYILGGKXXCWOZYRWCQKPMCBXGWEU9HTJWQESOSTNJWAINOBCLBV9KS9DXLWVRARPIBOXDGUWGELU9E9CEKBWOYLSCSMUHJEMLUUGTXXINHFKEWKYWERTDYFHABWGDVDBULGKO9JCTOZHY9TAUGYPRQUGGAFMFXB9TDBCZXCIXEHXBDPEAQPIBNPAFZNMTBXXUR9VTWVYHLWZRIKWFSPLHLURCIEWP9YUITOTOJBGYWHKTOBOUEHUEIDTKMIKXCIRMCAQUBDTAQRVBCMKFUDHQV9ZFYHJNUWNKECCPGDVSQALJL9KMGTABFJBJSQCWWKVVUJXEHXGTNFUARSBFQMOS9LAUDRXXAKASMRKIDGMCDOVSCNKQNLMYXS9UXTTKQXDBFSO9METVWSLZCPWOYKQP9JDSICQNZQLCZLMKZPSYPBGBNUAHOCWTJSGIGIRTKMJC9XGWTAJAYDBYXOBNSOOJPGQZYLASCSUXDDEAKSXOFHNCRXKZTFETLJVTNAYFPFBLNMN9CEUDNDQYZMOAEFJNCKPZAHKPEYXPDSNC9BQPVZNGXSZO9XW9UVEJRKXZKZVHBLSQOKBUCHTDXMUVERJUBWNTIVGJGAPTZGLCECMEAAVTPASVZKXIIWAXURYRZTCDSDNOTKACBNKDHDNGXVUHOQRHIVFCWFNUSPSYEWQGSHEQCUKFOXMEBOJZYXTPJH9QNQNVSYWQUFKT9LSKNCGZBQCHKXSJIJLNAXGIHMMNVWAZOAPJPETRGIOCT9ZBRIFSBDPXQW9WZTFLEBLAVBWAGRHCBSOFMI9JBRZRFLGTNPWRTPXU9CNYGWFUADTPLJCGGYBRBTG9JWUCHMPDBIXRLUXZQNHRLLOSDZYQHIPKQVZTVCQAOVLVRSNDY9YVMBBJMNCAK9FONINUSEPDXEXCVDDNDNJYUJVJLBYQXEFKUADAFRXOXZVXIORIRWEZWYFSCDAWWJQIZTMFUXQVUOIFCYWGXWFHYMFIXPTNYRRJGFAKK9LDZRULVCAGGVNOEAQGQJDMZPXQPWJDAAZAQPPAJDIATA9KIYVNXPLQFDFDLGYUETKGJDMTFIVYDREHPZBJHZAMNWHLMCBPSMYEIEHVAUTOGOBYDAQEDRBTLTGB9NGCIFYVVHXCIHJSUQTOTKXUFBDGYEIJL9FSFQPPV9HCCA9SGWFGKWQIDYRSS9XYWAMVV99OO9LPMT9YBBFSCILDHLELYRXCXDFCYMMDKPNXEZICUEWXVWOHBCPGATDHWRKHSNQYE9WWSNZMDWTUKFJZHMMGTQRWBCQKVSVMRBNUIPGQHKRKIEPJKOEUXMKHMRFCZMZSSOCPM9VZRTEIWBZZAT9JSYXIDOISBMMKXJWQRSTB9ZSYBIIGLVJYN9AEAJHIETTVRINBJWZXRBICPHGEDLUUCX9ULPBLFHSRI9GEWUYS9ULISTTKGWZMJUYBIGPPVWONUICOGQQBDOJPLCXPGTJRFBWDUAZSZEAJCZTVDKHNMSMPUVSEYFDOXGTCBBRIEMLFKIBOCD9ZFEXNFBCWNWNGQOXMMNXIMNKULQKMADPYDY99BOTU99PMJCTWKCTAGPDFGAZUEWCFEWYSYGNKGDKJDENSLAQKHFPLJHBQMWOWWMHDQFFACBASKYOSC"
            ),
            (
                "PGPSLKIOBGPHAXVN9TKUYMORDMASZEMHWTWLKIRSQRWBWBFXUDQWWXNSFTJCARTCBFKVWFKUXBWRMQOTM",
                "DATCPNNDZCELMZCQHRFIPFTADMSTT9TIIHYPLFOMXFBWAGMOOYIFYGCVKQUJXBNDXWHPIOAOKHWPBGJ99JARBYFQXBUMC9YRJUXSXRPPFBWPASBQRIHRTAKLYUCFAACFGOHYLYZMFJIXYUAMYVMGBKFZJIHBLKUDGCXXHPZITDNSZYVMUMQK9EQSZLTWGAMYWIBCBOBOXRUIPZBAYAACCPQNMPAXBGOTGEOQHDRTGBZZE9PWCGXHKFYZGWBIYNDIVO9KVECFANMYMAEELK9MPXQSWFBJVBOIKQWSRUMGBAFREZQKZULA9ACKIURZYZRXME9BEPOGNEMWYDTFQRPWQFGFRZQCDOAZNWMNWQY9UVYSSYEVOB9DG9ETQFIVRTHIUE9LQLCIGDDAKSOOKOOSZLUVCRTHEQBCAXKCHGOAXNUVQNBMKZQUYTJMHYSX9EQLLWWDHLOXNKDDAHYIHTQEVXXVKSWDSOPKCSCQEB9SDHCYEEQDHPBXVMHKNDQTZAHXMEEZCAZEYHISYXAKPRXKHRAACREAZYBFKEJWIXYQRZSR9WSRVRUOAGWUYOHPQYCYVDDZWOLPGBKBOIZVHJVNQRCLIV9HI9GTLGOBCN9DIVVBZULKNXMVDCBOQKRPKMEPVOGUS9GBRWOITNSNOFTLXWVAEPVNTKNLRRZT9BNQYHLMXOTQFJSERNHJY9IWMXYLMQHLTFTOSXGEKMQH9IZGCXIYABRJZWQWVZUNHIGBVJAVJOA9WHFDBDIIHWULDESFAUDECCQMVNUOFDVM9LPHWLJCUSPXQHO9YBTSPCGIMDNQXEXBFNUWZKTPMDJWMAIWLGLGTLXYHKFQXXTYZ9JXDYVNN9OBPESHVTNOAEILHFXI9CLAMOEH9YVPEGAKAQAVMATAOLWNOEFWQAL9BDOOJWYVVIAHCHZKGKARPISSAABWVHENWLWUKAKCRTNREQUWHAKJXJLTEXMAWWGMPRYZTJ9OEGFMTQAXLAHQYOGJHMIXRMNTFDMGERHBOQYYFNSFLHVOKKLLTYRJEPSJBCXWOOGKYAFLAXQOJO9TOA9OPWLCDYKXYMWHPNIHZQBVQAWMXFWWXWZGC9OBFPNTSQHVZNLTJFYZ9VLHBHVDIQKPC9GKPZFYVMJLHOTYOWZETLAKBNPBZKRA9VGYSAO9NFKCPFGFYW9PK9YEJSODXJBBMVIO9SDELTHDEUUJ9KB9Q9WTKMHZUNYPFNKKJMDFRCWMUYFQAQUGXIUTRXXWJTJOIQFCZXUUJWFGJCMMCTEOKWSOBSCZSBHJZOVAVXOWZUHZXADN9NCVRNVJAIONTOCJNT9LNWIJOSPQSABIBGSXDJJLX9JJIBTTIRCFTAKVEYHAAGOXPGQOP9LVYKZVLIQVVTYINTW9YLP9ABLXJAJBOPCBBWEVRLBOFZMKGJVPVHSVIZ9NIQFTXP9YBT9UNRKTPNNBJFIQWWWZWCLDVCMZSWHLVF9ILLYMXDDHDSNDAZWQUNSXLWEBNZAQLPCOEKUKWZIUSGEFDCRUNXFA9ADKDVZCVGCD9JQGXYFBI9OFBHYXHOHGWCYNQPYIVHUNOWMCBK9OALDWJHXSAKQBDBZEGTSBXEZYVPEJJKMOOYWADALDXZSCXKGGMFCFRCWVHSATCZUGFKJ9SSEUUQ9OYDNLMWXQFAGC9E9A9RIPZUXCKIRANWDCIVV9VRTMUBITXKFZQKYVACEHPZUYKQHEVAJKPKKRTVFJVDSZTPEDVDZIDRFGTZWGGJAJBFJTVJRXANJ9DHEGWAPH9POUBWMHBTXEQMJISDXIWXFGQAOARIYFVSWWVYTTQDNQCSDYKIRRCVDXDKBEIGBHOXRVFE9ZKRXUCDVPSYNKHNAGFZBVMDLLCEMYCYSRZKNMDKBOTBGRWOFYHGJ9IUFCLIRMUONIBHPIWOSGBQYHGDAPOHOZXNWKOANZWHLWPRKJKSZQJWHXW9VXFWCECDINGDCSD9GHNLCDUAZQGLGJOBEFJISZFTNTHVGRZCY9TSJSVRNZHT9GSEJHWZIGYETENKFJLVJYWFYROMKXUYGTELBCINMOENDEBPKWTJHUWAEKZMAWN9GLKMPMJWLGKUASQQVCECYGW9UNJYO9Q9WZ9PDAWEINFVLUVZSIXQYW9QHDKELATCTOGVZWEYBIYWDFQKSWALUIPUZ9ZAWWNSQBQNSA9UX"
            ),
            (
                "AKNFORSXSIBTZBDHKIJHSLAFRWVQZORJIS9VENKEWRUXEDFTDOT9XQWRLHXW9CKZWQKOSUUMVMGUFYDQN",
                "MTMTLDQPMCJOKUHXDJYAXMERBGJZSZ9WGSYNWGTCVHOQXTEZAZRCUDNMXZURPAMZXGNOSA9APZGSXNDBDKMNGLLF9MCKNIIFJDDY9ZUYJIABITVMEJABQAGTFHGWUZZAIHUAFUVACRYXPJIGGDFLHGTKZKNQAVNTDBWEFPXCRRTKYEC9KCLSTFPISBQ9CEZDOODSSIXFARXTWCUBDSFT9NBKCAMWNLBWBVXRRNMMWAAKLYVVIFAIORZZODVL9NIQCYKZ9LZ9SXWLOFPQHUPPYVNUZLJANVK9NVXWGROLDLWFGNSPTODAYZKBAAQELI9XHXNDVIXOYFXNIWOERIEFOQGYFGUAFEWRHA9NRWTEPBIUCRTSJWLDHZTZJTPTYOQGJUITSMYGJKSMNQOEIKVQDYEUPXEGIGAXIXLAARSCURNMTEHL9LSFMZXQGHLUATARUEYWYDVHSMYANFBYZACYKTBPJUJKK9MBXGYWUDUVNEWGIUAZGFDAQYTDZSDNWPAHE9FLVFNYBYMFAWPGWEKEDKUSA9MPUFTLRTMRRSDJCYVPULBGMMUAXXDXFKDMWJCSZJFDEQHJXMZWSQVEXELS9JME99QG9XUFVPBMARLRFBCAMMEGTQHCWOPVLZHEVVBJKVHHCYGCAVFUPBCJTIPVMQKCQVDKBDYVTTBDOHGSZMSPBWQJ9VVP9BBOTZ9WS9IZPXJGWMLPZXOKH9HAQUZLSEZXDHYEWKSVANYO9DSJPPBQVHRTRGKDVZZGDGSGZBSYSHFHYMTNH9YFRZOLQWMASNXYLCINIZZBIMMCUTHRHCCSFPZFLQMQSBKDWLCIADJUZBPSNFUSHPEB9IVWKNFVBDLOLMFWMEWUJJLKCNRGNXSZBAFCVNHEJVOUJ9CSX9ERMRGPKVQBFXKTCGTMLYH9FZQVQUSRUHV99KYIVT9KUFFGHAP9XIXQCMXH9ZF9QISCHDLKBTUMRYFWJVPESUGKMUANZHSOWBF9TDXFWH9IBGOAQZNAEDNFQXUGBTQY9WARAPXTSHAXIMQMGBSLEPHKUPSSJJXDYUQMEOPXDC9JAVSAORVCHIRYORBLJAD9IFWEAOAZHXVYAJDACQAVAHJKRRDKLHRFDFDEVSTIGFDHGTXVJDBQDM99DXHOLHESXENKZCWD9SSELIBQNJRIZCFZ9XAL9JUONAUDLOCSPHP9BRFFDNO9RTOQB9QVREIFJHCKNSFPLXK9PJBBCU9KLJH9SPMY9CUUUXEYLLAYSJKEAKBMDIQFBNYTMN9ICZSXCWXEWIDBXZOOHEKMBDVZAAUGTNJXUMEYCOKOWZBLHYBVPR9VNQJVNQUYAGDMPORGUAZTYXHKQTWVYKHLEMJEXKLORQQWOQPZHXHZ9KNZZPILHDUMXSBCB9MKXJJVREVANIHXJDIH9EXMJERRMUOKRZUWHBNRKZVILKTMFBIMNCZWXMBCKIDRSWGFIZSZXTZMFWTFAPMO9OGBCGANGZBFUEZUFUOUBMJZJDSDXQQYUPHIFLMTXHIOHJLFPQQJMCIXGRYIYZXFFWQVHSRWUPVQYAPJNPXCLUCHLULYVPCAQPMPSLZDMXFEFGUVPZHNRMDTAQAQOUNIPJ9N9XFJU9JRJ9UXHNJGEMHQWR9XKLZQXEIZNLKINQIDGJQKAHYTODU9NIDHKZTJLFRWZAZTBPWOYHPQMIAPOJQX9BELBSJCYKGBAWZLOPQRYDKYYZJLKVCBEICJEWLZLKKVJPJHOSVRXNFAINLSSFRBTHYFHX9YAMGUFBDHOUBZHC9FUZGRDMHJZEY9FGTL9ZATNEEPBCXRVSCPNBIZKNQXNPGG9LBJLOYLNGZHHTYECFTPSFORBBNMLSXKQPQXHBCMXUUITWPNPLHZRHI9GLZHUZUAZFBIODTK9LHUI9WMBTAUJGEZAWHLBJCTODBYJCKFDYJFISPCULHZA9HCLLVCUOIYAFCUAVQLFJUAYJ9KCLCCUBYNINPTCPOTZHNJY9TYAHQXZT9PWSGYFWOGLVXIK9SBZHMPRRWZCFVAHLWQSNQQZQDXXDYKGVZLFVYAQRWVBE9HFXO9VBTOCSEQP9KEWLOWWBITG9BP9WRKWNGYFUSGOGKRFBGFSGZY9ZOIKAVFXHVUWUMCEIMDWDRUAWQOZLNXAUJXIRFEBZMGXKVP9NCLBIFLQNWYXHG9QNRIGCMURZX"
            )
        ];

        for test in tests.iter() {
            kerl_generic_digest_into(test.0, test.1);
        }
    }

    #[test]
    fn kerl_input_486_output_486() {
        let tests = [
            (
                "G9JYBOMPUXHYHKSNRNMMSSZCSHOFYOYNZRSZMAAYWDYEIMVVOGKPJBVBM9TDPULSFUNMTVXRKFIDOHUXXVYDLFSZYZTWQYTE9SPYYWYTXJYQ9IFGYOLZXWZBKWZN9QOOTBQMWMUBLEWUEEASRHRTNIQWJQNDWRYLCA",
                "LUCKQVACOGBFYSPPVSSOXJEKNSQQRQKPZC9NXFSMQNRQCGGUL9OHVVKBDSKEQEBKXRNUJSRXYVHJTXBPDWQGNSCDCBAIRHAQCOWZEBSNHIJIGPZQITIBJQ9LNTDIBTCQ9EUWKHFLGFUVGGUWJONK9GBCDUIMAYMMQX"
            ),
            (
                "JUEZ9TPHLNUZCFDDPMHCGPDKGJWIHNUTCUU9DTXHLQMXVOVTRP9LQBXZZEEFPIWGTMIESQTKONSIKXTYQCCKE9ZEDXUSEFMRWDAQEJRSJAUJYNTPGNJFSUDXKO9MZDDNITYSVB9JS9GH9GJWHPKQONNRSNN9I9GB9W",
                "ZNRRI9URLIWOKNGWFPGKOLFOXMEHNOJRNDJHNHZSYLHTZJEKOSASCX9YFHROJGETALJJGEVPIYNXHXBYWGGXAXRYQTGIQGHPEOMIAWA9ZGKREQRANYKJCWK9VUJPPKTIZIGMMGENNBHHPVRYNKKNQUHQVKSBDVRTO9"
            ),
            (
                "KQQC9UAKEFHUUKHRIWLJNSUCUSSKWSXBMGAFRCWIBULFP9BFVDYA9SVWIMJOAYPBVIHFOGKSWSPKLZWIUINOLMOZAPUSJSKQKBFYDULUADLCHPTNAUHXGZZCQBXQHRRUWWOWHTPTGYWXBGZZEYYXZWENJWFGAQDHI9",
                "FMNEUQIXRFADGTECOKHWUN9CUTRMGXWUCUMKYKFHRVDYPJOJPEPFAJ9PVPLREBWGPPSJUNLUDC9NZAZQAUETYPSWJTEAMSRSPYWHW9NAQVMKX999P9SJJGQPATEMPVUQQCINCVKUCLUIDDXQYGLSRFGUKZUOEQCEPX"
            ),
            (
                "WBQNFCYCPCBM9MCEJZIHOTTRJYILOCVLRQLFYTLQM9NEYWRMBVESI9OQKFMAZRIXNVNXGZAVQOOT9KSQXMKYFXDNDJCLAPFWWSKRXCQ9ZNINLYEPHUGTXNMDUP9ETBHJECYSOXZMWWEAEEQIGULIEGVNGEIUQEXTVW",
                "GVWXIFONJFRXXLQLXQBUHSJDXN9GRAF9XJUCKFCQCBPFVRP9CRZU9XKQLFEWPI9DCSWQJNYCKJDVDLEDCXVVMUTJAMSM9XKXRTY9WJHPPMOD9TEKLOQ9Z9CUGBWKBFMQHHDLAZDHWSTOUOSSZXYWRBOMRZOSXWINOB"
            ),
            (
                "MKUGFJCVYPCTCBLWWUHIPQNPFUPCYDQAYWLVXDBLXKLBOZXMWQBHTZVWVDHHUKLESVWVKNJKAMYPYFIMCYPFYUK9MYHJVNJHQCYEGVWFBSDEFWBCIBAXBOCJ9QTYKPKWFNEGFTIVQ9QRLTYYNGEBGBUDYPEFDSLZZC",
                "JFMFFTJVJRLUBKVFLKZ9BVQDWOGRIQNAMCZVTVXARLMCKGPHWQDJIFFHSYDQPCKWJFFQAJVLIRWRGHZUCHNWGPLJLPPVRTOJVLKVTHTAVYFDTVHZBMWJRXZOMICFTJYIWOESI9BMZHXDBXDIRKADXWDYIYOQEWFVBA"
            ),
            (
                "SFTQUYNDAUXFLCAKZKKKOHUMOUTLXTFDCMDVOAT9QDGRVPJGBUG9YXVZDUVVQ9ILCRMEYVMWQXFFVTIITV9YYTTXJGOZAPDYBVQVAQYPORIJWAAPIFUTDZRIDKDGSQQXLARSSGGSUNPHZXKEERDYGSCDLPOJREIFMQ",
                "OBQYRUHLLXZFEXZMORLJGPCCZVXXMYZUYLEUJNFOOAAQUESYZCPAHPNVGRM9CUFZDSRJ9LPQIKCJ9XERWTZDKFZRE9ETURMEOHPJYJJNCHYNVOZJXWESUKHQCHCEFEKNSVMAHLRRADNAWBY9GVFOWWI9RDNRGYACUB"
            ),
            (
                "YHQZHLTBWYTTRHORKFJVIJIILPCYV9FPVIYSTYKYJSRHQKYRDDBWWO9TUGGFV9JAJENGXHNYPCAWLSHHEUOWJJYTHIDDDGXRQUO9VXIZ9MPAVZYFSIOPBWSWNOS9LEBNXVTUYJXYHXDXPESVKKZRRVNTXTUBPQGTB9",
                "BKBVMVDQTYKNWZAIOTPMBQULKYFXMWJOCVFKXXPEXOUXVAJGDOCVHSFPMUCDZAUTEOFXFHQMLVLDLAHLYEJBPYEXVOAEHSYRUVLOIJPTSBKPRSRMCCSOWWFGUMJUAADMRMPWDMOJABLAFXBZLLSIHMFBV9FRROMVGB"
            ),
            (
                "VXZKAOBXG9MRCGVWJXPAQLBWN9WYEINOBRTCECZQLGRKECEMLBFOIZEOFPRYJODXTGOWDAMNTOLUODGCFVAZOGABOUDAAH9WCIZTZOGSVMBVETINIBYEK9AU9ILOAUAVJMB9DEWNOBCNEHYTKVCHTZRBGSBXBREGXT",
                "BJCVBDZXMFOK9QLBUBUTZIKPZDEWDLGCQDJCJLMSTCONJFWVFYSTWPNUIYERHIKAKFPZXVDKAYARMOUKCWSTGSJURVF9NJZFIVLHAUGIOGSLEMKDP99UYIRQYQJGDJ9UZ9UANTXVIVMDACA9JWFVYSLXSCEZBYFYYC"
            ),
            (
                "GERIGQBQCYXSLBJGSDYLGREHYRXAVRFHTTGEBREAALQZPAOXYZZZTBIEQGYBRFIQPGCFPWHOWEH9WBEZDOEVGJQVXQCDLYVLUCTPXMOHRQTAR9XJFZVEJIHREDQCIHBAWX9BYKNZHLDDXLNFP9MKYJJSKMNYZWAVUY",
                "WVNSIK9PFZYIKBMPFJSDZSGDO9AVR99SKFPHUBPODJEECLOZMFOPRCYPYVAQ9EBAAVFBMXTPANYBFCHLC9U9ZYZALGFBQPIZMHAMUDPXAXYZBXIGEEOKCZKAUMXRKSOK9OGRWULYJKLUBVGT9UEFLON9MGLJKUWFVD"
            ),
            (
                "BFSAIXJPJJTZYNRKJA99RUOLLRWIFIPLUKRPVNEYAGTJHEXHARFVA9ZKUXXALRUZZDOJKHLKOYIFEYXOTZRHXTHUAWBQTDFMWUHYFSNNAWHN9LJCTVKHSSAPYXGYFTXVXKSUXXVYBHVJTURGRYHEHZQAKHNECWS9VY",
                "XSH9EMLVXECPMRKBUEBSWRLTRIAPMAJEJXSDBMHZUVKAVHQLDEHFJ9KKAVCRVIRMOKUBRTIOYYDMFTUAXOHSKPFRJVMNEDDTRUUEOAGXUJGQANIACBAKDHKVUSIIYWSEZPKSTIDZJCJVHFBSF9YGQ9JJBAKSSVIC9W"
            ),
        ];

        for test in tests.iter() {
            kerl_generic_digest_into(test.0, test.1);
        }
    }

    #[test]
    fn kerl_input_6561_output_6561() {
        let tests = [
            (
                "ZDVXRHZRIPSGGHWELMZ9LAWABXPSBK9ERUANCKBPIKXNBMJUXTFNF9VHHXECYZTUKSQTPNFCTXZAGNTRCMLGFKEDAAVQMBUREFLNPJVQFDINCDRBL9TGKQGLBSBEVZUZDDCZDRVSDBOBVLSZHGZMDCQPEZBFLKWUXYFGQMSMCSHYKDBINWXXKFLYWAWCNPCYB9CBZOIRCNMFUMKXNPWRDPWHNGLHJALXUQNMRTFNVDRDEVHJHDQSIPHGFAVLQAIUUDXJREZLJKBYMCXPWIDOIMNKZICFTCQWRHKAZMZBNTRIXNFYZGELISFA9UVSAQHVJABZNSPMPZGSLNFMDORGPKTYMLWFMJQXVKUHDGPINFFBTEUTXAHDBMK9FVS9GBWXIOZBMBTZMDDFCVUYMIWXXFZZAXINQIPFIYMDGUURJJOCWRXMCULCKB9ZSZLLGXVMQMNZQFMSHCK9TRWIIPIOHRRQGHYZJVETBGEOAGZOGKTEJGYAYBHVQ9VFBNEKXLSJKXAAFHDQDEJCZEAHZPJXCYBQNZJOTOZ9AUTJVPGQABNMTZWCZSULVMFSXDKKUZ9JAXRMZRCFETMGBLBLJJMZAVSAZAVWTUETEYOMVDF9GXEMYKXWMEJBERDTMAIGDLRHAZJUUCQNATVZIRVOGXAZBECUPYBNUDFUM9SLRIBQNPVKXGMXZFZ9FGFVNNGCCOABCYWNMNNSIOPFHQVRXXWIFJKODOGOPURT9HFQUKAQB9DOGYIEVQTESPSVNKWKLGTMXTDPKTPDJGOKQIZVOHBA9UHOKXXZJZLCPLZTMWSHRIQHZRXXUOZSDGBAPOLNNXMXJXZGQZYXAQEGMKUICIQTL9DOXAELENQLTBAXQVEYQBFVRSVQMAMIELIUALNUUDAZKZTPYHUMPXBGZSAZPZRZFYUISCBRLMJQLYUVVPLDFMHIL9DEEIQSZWOUOQSXTREGSWZKPQBVXMBOANYWQGVHDXZO9LQGYOEXMCGFJKZQKYQYMRMGHTCPCOUYCEYHDCWSCHAYVDEOW9GKTBYRQGSSJATRVZM9FPT9FQTFBGNJQMQNQIMFDSHELQFKAVQXQBEHHKCNDNANYMWZDNFKU9ERPRVLDLTFTMGSSPWAGYPJNFKFUMM9Z9YHSSDJLDGNAAWDZIDTAHD9VQDJVPSQKMUFJAICMPAFDZHZDANRAXRESAUXTWEFGWWZRHVYQOGHLNMXZI9KZ9LJIXXBGOXIDJUBEZYBOYAOCP9RLHEAXQQBUUSMNJWNJIWVKCZLVDYTFANUGUNMZFFTLRUCMTCZUPMLVODPYYNVLJOSRNQVMORMMJYO9ZDXYFFOMMSZONYKENHMYLZPLLIFXKRND9CU9XIDMZFKOFLASVVBCVOXKZDOOVDUSDKVLSBKXREQDVKXJCIXCHWPXF9P9ROPDSPBSOYLPEQAGDYNLMBUOBIJQGUE9NWFWHZW9VJNGVAIDPR99KZXWSDETGXLOPJUZVB9VFLDJEPOMYJFAGXPSMDSXBPESBXDLPLNAGSPRKJYVEKHUUXGRLUWLJWBGCQHVFFTTXPWVEAZXW9EXDREDNHOULFTACX9QBZEUPORZPBTDGZWEKQUQTTAXFLDLUULWRBBEKVDPISONVYIXCSVEWPFGRXJJQBOYEXBVUWXKFSVHCNZXVLSFMJHYTDYGZUCNKORCAVZYGYGLAGTHGRUCZMHKFNIKLMY9JBRDAEKOJRBBWHQBUGCFIXBNNVCKKZDXLIHBJYXMLYKBLTYHQLCFBCXQARHCQXGIJS9LYSGNPWBZE9DWNJ9O9WJPYZEYKTDBJDHJZONCWVAMPMKVDEOPMHTYOXRKHE9CTXOBAGVFJSWFBVORGPXTBEYMMMUUALDST9OQHG9NGUICAFFRSEXHNQCZQCCUBXMWHCPZVSLKTNOHRLLZXOIRQIQCJIUQNDXVGPEISBIAXZNDVOMCDLTGJEBMHNYVNQMLZYNEQWRBNGFQOFDRCIXILN9QVKWJGVXXIFPVAPFELFSR9ZNNJGIUCUJWVIETMVMMTPHEKRZHJGSG9S9PCNYLANUFAIQTEFQSYJGBDEUJMAAPWQYBHZLSYSNQHWANATOESRFRIFJPDNRVWKDQVFLKFUXFCY9SBEOWTXPQGNUQJWLCRVFSNQPLGSQMPWOWJJASPAYPHQRLIGBGOMIZ9AIBHMFZJPJSNP",
                "UVYUPXYNXKSEVWKECMJFNIGRMSAKOQCMFOBTNWQCJOUIDAXSWSLLSPFMSOPBGCOQC9FCTYBZLTFYVNW9WS9ADNGWLBG9BKOZOBKQIEIDLWBCODAQXVPJGYTGTCEMXAUHADCONGMIEKPMXQVNUNXHIQHNQJIJRRXJAZVGHQCQI9WXEKENXRY9OA9OUCNEFJLAPOSLRUCCESYCPAUSUJBMEMD9T9NCUEEYODPPELJPYKQUAAHIAFYFQAVIKLFGPJUVZUQAKNDTRTOOWODBRSXMLFPIHWGGLMWZGHEGWNTBATFOFBDXHV9DEXQDXTVZLGEYWOEZHGYCEZNAAAYKSEGBWUVQDOKNVFE9TNLIOWJFLYIXFKITLHVUYNPGEPNQZANUE9MFPAO9YKJG9OKIM9KQZQY9OXSJ9MRRBOBAWCPNCOKAVTMDBSOSAHZJBLABIJZEDXWQYAVNCUXBSGIAGJLHYLWCLQCCHNGFPJON9XNGIGVEJSUAAKUGQXT9KHYOEGGFEY9TACL99D9XUDBZOXF9NQWJBATMWCWLRMPKUDZEAALRXZNELXEREFBOXGLSZJQXMKFFNUHZFE9PRBCOTJXGNEJYYSOJJALXGKSQPTFQTTKADFEUIDLIQGQBPZT9UNSVDXM9HFEBLCOKMJZTXYTMQYJBMJLEPBNSJBWVYGYMFUIOFTOJXZZMTPC9TFEXRGEPSAWPNBMNWFCKKXFEXKPWKGEIDWZNEAVFSZOKOWNMFHHVTWPQINKJDDH99TYHMBIUQKULWQNOKCTOVKFBPDQPNMAV9TVJ9GWDKM9NCEVUZDFPNYTYDUHYHGYN9ODSMFDGQSVWOJBYIRZXGCCKCBYIBFELLJTWKMKBOOEFPJJEDUHGKFFTYOXLRKGFOWXNHZNUZLMRYBKPSPMRFLIYMISAODJSJM9IEEIECJXTTPLMEFVTDGS9NXO9YTTLKNAVKKHIXXIFNW9ZCABXMQPF9UIUMFDHPDUHYEOMKYLUWYYQGLLPUZKPYKHHPFXFPJRKRFJQEBGMDEUYDWEDDQNORPYY9HTYRLSDDABBBACEWMFEFELZSLRSIFMEHUGLAFTVAUKNCHFHEYVSGFIBRGLBCLZRH9JTYQKICRICNQWWTHXGJAYBECNIGVDDJHHOHCRUKIGIGNPWTOJZWPCVYMDGGMYT9RBEZOWQQDUVOZLVM9BNUBLHUECDVLQWZUZIVCZYJWDX9DXVDRTGX9YNMRBWVDYJRBRSTOEJLBWQM9BPUMY9XTHSNKGTUVPDTKZOXTXTCHIVQKDGZJXGUULFMSFWNVJVRL9ZUNTOPTFUVTBBTQO9FDGCEHVCMGGYIYFMESMKMBJOTGTVWKCAQFNQKRY9YYGOMPLGOQHEBIWUXBSYLEZPC9RSJKEOURKRWAZLEQKSXOIJRPANOIN9PTMC9KRXQFFTXILSTQNBVUNWOZBDRAFIVPHFCYIZPCRUALMIEPZLHFNXYZLVGDEBIVBELET9LYLDKLUSSA9IUTTWTFNFJYYFBZVCNSHWMIEUTEOFJCLJNG9HOBWRBBUOCLSIEQJWSZP9UGQIGKGCMZS9SMAMSNQIC9VTFAOITNNTNIBRZPHVJOTYUBGUWEKNRYEXGDWFHFTDGGIDXDUFXFUXREYHOWCDKVRRAYFYDWYQUWFV9INPWXUQMTHIHDYEJPJASDZYYANPWNTPKDM9JVDNXFAXWHXWXBMWCPLJWCTKADMWYZEWTJURDOZYANFRGFXIOHQTMATPXDJO9DMFQWDOH9UIZH9FHGCJHCBASKZS9WSQGHA9TWRWMSQPYQWOQMMJHD9EEVTOPITDCFADNPUCECFDNNAPUMLLJUWALOKNNMWCGUWB9GFS9WMWONB9KJNBXRDOHNUFXKCBIAXMMYVLFDIWCVGLYVALALWNNNLRTZNPUYGGMRGRJPZFTRIJQ9VXLMBMMXJ9QWZXFETKZJFKRASFIJLQVEHXOKCFZXXJFJUDSTRIHRUEZUXJMTLSYYKPEVEYPOUUAZNXTDXLLIINALWGIOKYZRHWMWVIBXTETWKLMKOM9EYVNXMXBCSJZYRWHNYNHAIREVIUAPRETPWKHCIMHWDWZVVPEMWNKAPGTOHGOAHOFZHVPGPWCXRMVQHUCEXUJB9AZNBPOTZFMSNLADLSTLNKQPIKILMRBUU9NWDBJNNRRFKVRNUWOZUQU99"
            ),
            (
                "ICLPCHVNTEAFBGMCNRRJVPAMUFXZ9ORHNNAMNXBFDIXOMZAZCOBVVOGVFHGLUPRZTARPHHFJKTDPNFAMMDHOHOXRQICQCVXOAHADVEERKUVCRHMTIYTBYDGNTAQYMWRCWLRVMAZINJPIBKCKUXG9OPVK9JNYVNQUJTJHFOGTEBIOTNGOOGEXZDWYHEREOFOIUKOSGHOAYHHZXERGLONEYCEAFLSQK9KZTUUVPSZDOFEWGYMOAZQH9DDIDMDPBDCCBRKDIUGSDFSWEGCDZ9ZRNAKZNBRKGBZ9VERBCHUVEZHNWMIJAXSHO9F9TMKZRDCTBXVNZGIMZOE9JXADC9JXOVBPPIMYSGLYGEAQIXFSAJUUXZVTKLDQWHBGSSSFSXOOEAVGLGJXBFQFZNCWDIGWGX9NBOWDTOJN9YUUEQWVHRXYHTIAJORP9IRXIBCZX9HCH9QZOWJUUKUVPXKGFVZUQVP9WTXVNPOXW9YJTQDTSM9GXZVKVCWQQE9OLKTFP9HDKBKWUUNIACUPZMRZIGYRSQ9KMVZPZRNFRBHHVC9RYUDEKUANNKRLDKOQXYB9IYKFC9OVENTXOXZKYRDLPG9AOSEAUJSCYNSKOWYPVMWMZVUTYJNQQXUDDKQXKYPTSHBGEB99XRTCXDYFVQPRYDOSPXQWP9VFGEQDOHJCQSRUCZKDNFZT9NAXYUGJBCNWDNJXTUJEJXVZY9XAWCCMUCPJMXVLNYSPCTFLVIQRONHAQCX9KHDQUKWHLYDFRLGLYNMVOOJX9RRGNTYBXRCRDEWMWBDGEXJHZVHGGZDNPTXJOAJMWFFXQXKFIITMXIO9DBK9BKKIEANUKYCIOKVVWLLWMCUTEWEVHKOSCBXNTRSNJBQHVMJVGGLGD9DBYMCECXHMSAXHDGJURTIXEBLKIFNSXHAHSXOUJIBVJXWDUBVFUTTPKHPXMOZUJOBKFRVKXUGQEBFCRHDZHGD9NDEHWKHOTVIE9LHNHIANRSNKEMUYIYWKQKOIOWH9ARLBLEDWIMMPHB9KSYMEMBOTYUOMGAGC9UZBYSAJAMEDIGWZOVARYULPDVZMRXKAZSBDGJBAUDUEIQNHCCAEUJUFHNPYCWETTYPEXXQHLAAYBIYXAEUHEPEPUUWWLSMJSMBBJSUEFQFS9MAEEJU9PFADGCGBLCONZAQJAREJHVCCAENTERTQLFFPXFBEHCZCTVEWQJAZVFDNZTFPAURWMCRUNYXRYIMOY9MWRACQLBPHLSLNAFZNQVOWRILTN9YEUNMAWCEQCBPSIDPYUHMHUYBPJ9SYWNYHVDYLGJXT9NCO9XNJCPMRDMBYYFIZYZBSZLTOWONNYAVYXJBRUEAVLHUMDQLV9DEAZGNNSLHNIXGULXSSDNRSLZBNETUTDBLJVQRNYWVSFVMHSAXMBXQXATQUXFYOMQPYLNBYDKTSHXOCWBXABZLOVRPWVXYBUFZEHWVZLVHKKQULJIDQBBSQHINPZSYVWYATUBYACWCPXDFVEAEWBDISBOHPLFLKVHORQDAXOQAUGDWBLKKVCMLKXDAKTKDCVAMUEPUR9BGKQFRPRWHKWEBMQLVQVPACONSYVTCIYSAX9BQ9BZSOCDUMEJVWGYWEKSZW9RNRRNEJIOSRPDC9JMNCQRUIMOSFXGEXOYZ9UBTTNBDL9UUYONGKVZWCPAIUUDWKIWGYFYBGUE9YFPHJFXPDPKXRRJWHVH9YCNYSPMZBEGOCHPLSMJHDQYMDJCLNNCJAGUK9BZQXRLRDLXLJRAOUBHEJKKKEDKMYDQDYCZILMPQTASPMMX9DZNIORQBRORXMTSFN9WJFHWYMRBOVCOWGYOQDAEUAUAYLQEPHRJTUUHRPF9VVKFPGRGTQUHRMRTQNSSBFZPTDRZYGLEEMVNBMWHXERGDBEB9CPTMHITREBLKKAIVIGQNMGZAMDCXFVEMMMKLDVKXNPEXUAUNACAMVPHNDSVMMUPDIM9TGTWWQFJIIJIBKJEPHEQDX9X9NAMYWFTXCBN9FV9GKVVNEPE9GIEWS9QUWTCJQYDFYKXKKDWMYIREAJJICYUUERA9GYER9DUSS9TVAKKMTDRQTVGMAOGTVDR9YQLNAGMJQOQMQBVJVIDCKJFJLSGDBMKZATLOT9INBRMBHWEORSSJCDCMALMSMEDQAAVYSZQWIOHAJMRECBYWOX9HEKGP",
                "AJ9HCRUQOYXTPCDKATNKM9THEMSSDOQMFXWRDUUMERSJNVEHEQSNJTHIZOTCMEOUCSL9AOQGEDFSZWGOZDRFXINAKA9NEXQWPLPQBPJCUKWFWJ9BKZVNZUUXPFUQEJSUJSDQADRQRPXSPKSYMXCLAMK9YBAJSNCBJWP9CQTEOLFKBGCHNEEFAPAPUOADACBXBZWHLLGCODFZOXNTPBNOKUAJNHBTRJKSQWXI9PDNBFYFWSMDQACNHKAM9JPPFDOSZEKHOPBGSKRVBIXDMYAWNHUAOPMJJCCODLZ9DLWOCKQJSJGJHVSWIBLAUJEQQZLWTNP9ATWYOUZADEYIRUEXWDGKRSTKYLCWZMWRARGNDSKQPM9GMTLNMGQNZJGVLFTSLWJEXYIXVGOAKJXHEKUIDBQJPSYGAYCLMOXSTK9QLOROKVZHILO9VDVSPHRRXTNJBCCXBGK9TEIXJSSA9LOPNYFQWXM9TDHYA9JOLXSJDY9OEKNXHKORBRPRCCOEJJ9X9OZKZFYQNOWNIOHSJTJZIQAURUUCRAVFEJRIYYJHURLPRJEIETROHVWPOGAHEFIGJGWV9HKIQRTVLJODPULFLUTMWVYAUFCNUTEOLXXQLEBLQFAXUA9NCH9VOQANZOQTXXALURCCFGAMLTXXDLEIYFOJGMGDOWTTDJTKQ9OCUMSQSCW9YEKPOVA9CBOARZO9TWKDIXACLTNWFXGOQBC9GKDAAGRLYAVWYWOJOKPNEAJQZFQQIRHKXNABIQFXZWGILBKAHZJXDUQWHBTDPMMRDWOIVYMPEPVHUAAESYQTKCZRAAIEJGS9DITALHTKFPXZUCBOGYO9HYLVPQQRAWOBM9VHBPPZ9HEGIYYEWUCSM9HRFTVCGD9XRCXTQYZ9IZGFHSKWPDQQKGCBHWVLTERAK9GVIFBDAFDWXG9UCBLZS9YBCZHYTFDBCIEAKEETDOUWAYJXY9CJGOMCMZAEEUTHPDUWLFLVSNABZMWH9CZVEUB9DZQJZGRGEQNO9PWWZKJEGOHBUPWHCQFXVHOSBRCRAKLUZCOUWELCL9BVVLL9UCWJLONZAFLTSDIJEARGSWEFEWSCYNL9HXLTQDXCFNWNUZMURNUONNJQYHIESVRWDQENCYAICJKUTUUEDIKAWRKYWABOEAWZGHLOIYYVOAVJZZQPVRGIAKBXSDCEWTMMH9FRWCRMHQY9UFRGSFENSNDEIMZJSMJNAEHOSRQQDGLHQD9DQWZVQBXMRCILXHIRWWNKKKIDPROOFMFWCEBKJOLSXA9PLEWEDDFBXYXWUESGRYHSQJPBOKEBSAWWEAXKYGKBIRGHUTIOUIRTWADPCCHBXQZVHE9MBPUMAHJZVVKOEIMENHU9AQTTA9SQDBKTVNRFAGGBXFFXGSOCZREPFNUUBIQ9SUACHDJOEAMABBSYKOBJHIYCHOPTDUWWMTEYGPOFYVKLPBA9LOMWDDQWNV9ELHTRZOL9YMNHMX9YKNAAAEWLOIZPGZSSUNOLNOFUSEWMXXZMBUAFGDVHRNX99OGXUA9RLSWBC9YUNTIHIWOADPNPIL9KT9NISTTTXEPQDV9MGQGPAVGCOGJDDXEDTILWHUBNVRRIBGYBQUADWWYCYWJGMCP9TWGJEQHKTULPVKELDNIMCEMHLJDSTWNXAFLGTKVDBRVXOFZY99IFXITIT9SXJS9SQAQYYDKXDISJPFUFYYAJORRXQUWUAMUMFYIITUOOUUSSZR9OLNXFXKULRCKSSEPF9HLVNSY9HCXWAVAMBRJIMYKLZWGNQFKVLEGKVOSVG9KULJYPAXIJEXTLUOU9JOR9MYCCWVAZWQBZXNNYHVCEHULQJBBJ9IDWLSKSMMZAGKAXYNTQFUMXEYVIVEAVLVOSXOOAIRTZFUHBQBNKDGPCLTAVNXPTJWESBFUWRAYIQVFWTB9L9GWDAUASPFXDVWQQCX9IEGAFSHQVRPTMTGWSCVGQNGRV9JJASJAWAQSOLUYXBZHFLYGPLHSQNVNUTIJXEREPDDBTUTBIZI9ORVPUFFEFAF9POTUSEIGJGXLTHKCMMXU9HWIGLXW9ZWMNCRADKYIZYFXFG9BEFIOLATIFOGMVENSTQAZRJXIOVKTYCEKMPGI9WEAAORAJPQWRGXHZJAGMWWKBHZEMPVNMYVEUPFKAOTCPIYMMAPZXSGVZGDX9IHY"
            ),
            (
                "CSPIWCWCZEM9NNJXQOSUA9EI9SBHYVQZISITDSJNCYLMKDAUXDFLFSLSEUNCYXRVLCKMJVXGNKQQRIVCZWRIQTDXSDQMDHTCZBBNCO9KEGMJNHUJQBLRXQYYMBXZNMZGLDRSINHCGJNUZJDAMXZJFQWGPGO9FCNYRTUT9UZPPMZESAN9MRZIRVVBWDDPDKME9MBHPJQQUMCJVDP9F9ZCFDCOLNBBSUTYDZQZ9ZQAUV9YJYSO9JR9GBJUGNKSYMDQGDXHPYTWKJEUVGPMXBXRHEOIH9DKAVMWZVNZRHCQEANYXEDNWVHEJBHRO9CVBVSZOWXRJJWBFVZXHZWMDF9GY9TGD9EMOFFGQWOTGBKCEKYZWSFZDHYNCEJHNX9UTTIUXULQFCT9WAAQCDTCDLULJBNJUBNWCQCHGAPCMGOXIMAHBFCEHDLRTVBJLGXHCDUQQDDERTSNKUZYNQCY9DONIAKVC9UKSGRUQHEDPZPZ9ANKLIEOSJUGAFUCLCPELAVOACUMTSPAWWQCKNASXKETOOOEUICMUOPQYJAIGLIZUDGBTUGUWUSSIGWSBCOJXPXKPEDIRFBKDDUHHYD9PKSWPPARRYVDGEUALRCDSOED9IRCNFRIQKDIXELEBIZUPGKBXTJYCUYQVWLVNDVHUJGUTGHM9IFVHKEYQRMG9KKZRUXXEEHSJFNRFZAUPITLRVJAXH9ZLH9FTJMENVRUWICSBCBIPXN9NMCKVOSOHHHMTBUPKOMLCZMPDSEWPKWSJDTTNFRPIUYFSV9YGJQDQMSKCNCHVUYGEOCDQPBAAKTPNEMJWXQSIGEFLWAQFMGQZLMGKXEDGRCEYGSWOBWUKQXGZNKCUQBOKNXHYIVXWVLLTXOYIYYWNFKZZCALHBFACLJAWKCXTTHNRBXMB9WIWV9CSZVLBVPLBSFXKXLWKYRQMNFZDAWZUFLWGWFKXGJTFZNKFKXL9SMAMLAZWMGDWF9XMCULILXVSCZTYIOOIBNUAYH9VA9WYFXBSNTPZ9OUISROCPXGBJQAUPF9UPJXESMDMOPOPUCREERRMXTLSCJIONAFMYTIDKRMMPZZJNOVGMRF9BTJVPI9PHBQO9EBMGGGFVYEYSVTJSYJPFYEJLHKVSKZYLQZCVRMF99R9S9MPTYHLCNCXHTWTMHDCRCCOEOSHSOGLPNNMWYSCJKDKUNHEZAWMFSDVMMEXIAPVRRKONFWGEUBSP9IEUXEKKNTSYGONHMWETPWREJEFEZGUKATOJ9UG9EVUZIDZQKYDRFKCLCHRPLQYFUUJATISOFMVDLGIRMZNINQTAZFMXGWMICKDFRIKGWAXRMPJKTHTGGDCUTKNGYAZHL9TSOSDC9DKVZEPMZGABVSHLGJALJPYRPRZIRBOAXAIMKMBLQGFKFBOEFULSKPDRGDBYFYIMMRSEMBKPEMPJUIWAPABZKNOXJQZZPKSENMBFNLOMUXUZVNJJTDRLGNDG9JXPXMAEOXSNQUPZBFBLHFRIZUTCEZDUIFOJEAOMPFHMGNQKE9VVNGXBIHHNCAN9HYYNQTTFOMUW9TKILPRZH9RIYFVUKJF9GCBFX9YKYBTACPL9IXPQVZCVHYXJWFCNACRJPIHRYYAAUFHLFK9OBSR9VWEMOMPZPUELASECOXMTOHPKCXHVFDPPJFVAGSPSEAYRYCP9PLKHWMMCVPOTDKMCJNJNUZGFHZTMGYNUKTJOTVAFKJXXJJIMAYXG9JLKUTBOXXZTT9KWOUDUCLXPDAAQOBLNSRBSTV9MNGBUDYOPPTZPPUAZSQN9HQ9XFIUZFRZASJQXZSQDWSSPULLCVNQWFXPXXZMWQENKGTUROQNRTUHMEXUBYJGKNOKHFLXZZHXPGPIJWZ9WXVCOFXBXPSXRGRBSLDYXCHSFZSNYHYZEBRKHYTZICUEQED9GHYFLBQAP9NUSIRFSOGINCUSZDUMPLBJ9DKIWKDDZKFOCMJZQFHUEGHOBLPNVVVPLABYMQSBPWFKPJE9HPZNFEHMHYLYPGVVRIGLEYIGLSGHEN9VAGUJRRTIO9HPLOJMRE9VCVDNPZHFJZJWFBBXGNAVNFMPEUCXMUDRJLMYHZMQ9QPSFUBAYRDTWKQNOZYZFPKOOQIFQAIW9PCLVZTCFRMQDUHATAKLLCKORKTYVSPWWADRANADXPVARNGZAHULHFUCQLNAOJ",
                "DTUVVKMIQHIPFKAOWUXNTAVENPMFVFJ9ITLBAYTYR9SITVAOUWWPENLJCDMVLXSSCUAFTNZZQMFOAHWXABQZEFNNUEUIBFBNWVJNIXPPF9JNAUZ9B99CJKUQR9RMZYZEYCOOSPJESWSW9RYONBMVBYGA9SDBV9HRBCBULVUSDCEMLAJNNMTWEGLIJVNR9WNHLHFASGOUHCDKXCCKLKCDKZPAMWUMCBPYRJPOFMZA9ZTPIZVHSIYPQAUDNUUGNTXZKJGWZB9KVKISYEA9UAZLRQCFYBOOXFGZJCKJGHIZYNRCBPBRWXCEMIPWFDGDEMBDAJUCZSCVJODTIIVODVJHSEYPWRVXCBGCMKRTKXOJALWASGKTPE9I9OOMUXFFI9CBSETFE9CGZWTZISXYEVUHC9SEMGRDUDWACELWOONHVRIYUXXWCFOCZEYZHKCRZDPHBGJPKYLZLIQEEOPZVJUOCLDRDZBQ9NLDRWNWGWCBLEMESMCTPDSRXSHDZAOXFPLCONHIDRHDENLZFPRWZCI9NPORPTFUPVUHTPAHX9IFFBFNTGBESEM9RR9SWAEISLUNBBZYIVJSUGTHULGIWEOVRFILLWUN9UMMPFFGOPBFOMPYIGMFQHPJZEMS999GNQYSRLLIISMYHDWLJHDSSAFSCUDICZLAKRGPEAKTGKFVNFN99WZPOCKGXFIJVYMDOBKWXTDXVFGJQYKUOQZLIWJVRJKMCQUOOHDAB9LEDAWPPDBTU9TDIOIJLHMYMGFOMLMNHWLTOKZJBBIA9UKPFLEIEQIEWHJ9LJEIDDVDDIFWYYXPVDRHDGAYDEV9LBLIEMXEBINVQUWJQIEKAKJBN9ZBXCYXUKD9OTVSXNWCCCPGRUIEOGJXOMLWBRXXKZYQ9OSFQ9XLVOJCOAQHDIH9H9WRHNIHMXO9AKMQOFZJSJBW9GKJTQXRRCQHFDVCLDXUUPXYYSIQJAOJGTOW9VTJXXEARGRRSUAKOPROCX9OSXYJFCLDKCEKDNAOVSGVXIJIUDNF9ZKRFFLFWAIKTAVSGVQEMUCCOQFTAAMEAKLNEXNCOGLDHSYIGCX9CEDCNPTV9VVY9WFDIJIYUUZKJQYEJQPRJVZYBJZJ9WUACLJIGJVMBCHTMDIV9YNXODLKZYQAKGIIOVJOJFRWIZRHCSQZLHHUTGEXZOZDVKPZAT9BVIDHOHFQUJ9RNYSEOYAJXHVFZEZBYD9JMOBIAFAFTC9AKKZLAQGRKXWXZOVATWORTWGTRQSWEBYAMYLODYNZIRQFIMNDFLWVDRDXYXTBXGBDLOSNTROC9VRB9OQBVHIIQJHCB99FCVCEDBMODAJEIHLWZNAYNEHZGUHLJRLDPAXKZWCJTHEAZ9JAVQRFWEURP9BQ9ZHWUUKLNVBGPUMNYHVDBBHBTQXEOQESQVRUMYSKJYDILHOCBVICYIVROFZFMDCCCKIQOQ9RFBUNIR9YLVCPKGMGFHEXLMQARDJTRISQBIBTHPMILBOBIWBQAWW9QNJQ9IEVWA9DXFZVDSTLV9EDXY9PNGAXJDQBNZEZWXJLSRDT9AVQSPSXXJZEXEVXLYK9JGILLDIWB99SZQUTS9C9URQXAIDMMJULKIQHDCQIHDMDY9ATXKSO9N9NJBN9HJDSTCUENWF9LW9GHBRO9IHUPFQRTIUVPGPFCOLLSHUDBAQGOKNLIEHZDFNYBFHYWEBRKSAYULQGTZATVE9SGYVGCOKAVANMMFLVOMZKFAXETTMIYMNJQDUOAEUUOTELBXUTYJPTZKDNLNLFXXHWKHDQKRV9BXSTNOYZDMKKOLQPEDFBLRN9KILPUNNGN9PFCZNKXOANOJBTBUXSICWPJAMSXGNWYIWTQKDXPTJCDWNBIZCDJKJILRAMLQVBPIKEYUOXX9IFWV9PEX9HLV9NQZZRBJKSKOGTAKNAUXBSH9LCHQMNAULWVBQKPESKVRJXKNDHCALPYDEVWOBFGTTSBGQLVJYSWTCLZKMEFRSZODMFLSZMAOOHVKEEBMMC9MIUXYOAWBBSJDZQ9NNGVUNVSIDAYUMPPLY9SPHQG9U9DSNKLNPXIFXDSZJZPO9QLCNFQUOAVMNWPEFHZWIYXI99SZPZHQDDWWPVIDQCNZIPIAPOOVWAJIDQJKOUIHNOPBHSVCIMTQMLSSXSADUVDSFTRXYAN9GYDEAQSEWMNNZ"
            ),
            (
                "DDDRYVOGWEDNJAOMAWNYEAKXUJZAONJVZRHUUILMZSCILHAYH9SDORTPZALMSZWYVAEBAPFANWFQPULIIBBBWDOLCPBUEYUQLTZFCOZWNUKGSEKZGBBONG9XNJXZWBZDGQVKIOPWXSNHRNIKI9ADLIHSWP9ADXE9NCNXDZ9MVUYXPGDT9EYCQACZZSAFC9VDULYDDBORIZNEPSPVZNVQXMVPLVBEQJAOIMOPIJHZ9YBYOZZKMEOGHGNLNODJ9DFHWIUMGAMHNWTKV9BFSFJKUFUBAE9OHYWHEAFFVOCTJLACLF9IWLHJOOINBJVHSNVKATLOSZLARHCSDIEDINQLFJERUWHZNJRBOFQZCZPEYJMJ9LQ9SIZOZGOZLKHCJDIDIRFVGKQK9IASNBYYKETNTMOKTLMWQXOROVNYFDLZQO9UETBYOKMJGMSGGGEIUWVRBXPRXBCUUZFUOBJLUQEHZROHXVOHKPTNMQPZGOPOYPXWBJMQLBJHK99RCMROARKLCOKIFEXYRVRBWZSKVCCEIZUPTCPI9VFTYJOJRMQIGMQABZD9MYHBSGYTLKDZM99BMHWQPPZKGCBOJBKX9AUYDMKAVGLYUHJHPCYHETYBCVHRVMGNMZTPCNDGWURKQJKZQZVIBPTAGO9WFPQMPMZGLXUYQUNLQVCKWCDVLPKSFJCDYOJNNJCZHNWSGGAVGQP9CMU9HKIKUAATDB9BCQBDNWCOVFBKVBUWGGZCJJNSLVRXBNYXQZRPBLTBZ9H9DNOYCJXAXZZLNQYWMPHMQBVHJUBXCHJKLKAVAXUAKXAQCAKVILHQBAZQ9ZJJPZPAKQXATPXMMRSDIXZNXNLGK9BYVIYXWKUY9RZTRVQANQSPBF9VECFZFKU9HJIVZUOWXMFHEXEWRQNFMEO9PZUTNEKMILXEZZSYQLIOCLOJPCQYMDCETSYNLIPTHCSNOLNFEAOKOFFRCJRYPQIWVQTCTGCRAFPKEKCU9PROPIHDBH9FVLBFADARAZPJSUBJWN9JZBRTOFDXPZGCKKENROUKLHYJCQOMPRPPNVDSQIFI9FKTWLPJ9MJMZZBXQAUMDYRPMNSDVXISRBCXAEURAXIEQJNIVZZDF9UYEZNAQABOZRJFTZIZTDTMJPUXOVLJCNCGOVEWRBFPCJMKAHDAHMINHCOYEZJXNDFRFNFFQFMOQVXJFXRYFLFHMRKXSEBAGXYSQ9ZJSWRGAPFBVOYV9VNLALQXPORKOAOXJ9LVWVCUNUSBYYCFMAFPSUASQUFNVSKSPSEYISRNGKVVXIXKXOQJCTIPUYMLVBOC9HHJZZQRBIPAKDARQVUGBEM9AJRBWATTTSYXPXHXJOJXYW9PQIWEEGU9GBUNUQYSZODPKFRQHNVGRJBDFCNNQQAGYGRRFZTGGBANJBD9XTDYEAYBQDEWRGYZNZOFVE9N9RMFVTVEQMXDKBPPLHKW9GPGURYQFYHLLHKJPDDEDXNNIJBCDDXJIPMHHDQPGT9OSPWCJZCVEGRUHWIGTMCCFR9APUROMY99PTZWVPSISTWTSBU9H9GPUXDLVVIAXBFGLIBZVQJLUXHSDKLMVKJFWYAZGTJPPOBPUXYSZIRBFLYMZXWG9EPLNX9ZOWSNEBIPWK9DTNRENJMGDEFMYFXLYFRLYJWPHDDKHEQMRBQVOPBLYRIELXLMVPZXPKLRAVYFEDHGHU9WUI9ACEQPVCSLIEXTKZGJXVBCKILKLAKOTCLNXYZNSLSWZYSVZCBHZYMMHPKSOAUPZPUOWZBVFRGCDUAVAHUVWEBDKFQTRTPMAAUHOJENJYJOFGCMPDNZKOUHRADBJV9P9KEPITQGELGKXKROGOOWKBDIVIMJYLBBSVDWJNOQEJP9XGNUBWYUYPGYNFQS9LUFXCKVJEYYHLL9BPBBICPEHCXDBSQVMCEETDIVOZIPFGMOSZCESCCMCTAIKKYQDTMORNCWLWQENVNTRZKVKDVQ9GEGIKIYYCITWGKDSVUEKCFNRRYUZTWKLXECAWFNKFHNPUDUF9AFOYRSUVLPJE9RCWJNQWSZDG9LFUQNPGAGZOFZUJGIKCJZDYBBGHXZTYJHSGQBCGGTUTRNFOCDCUHHPWLOZXQSPLJJEWWQZT9UKFAMNLOMPUGVUY99WCLGZYQLPIBASGPUSADYEZFSDAVXFCENAL9VPZWYMCWTLGD",
                "CSC9HPBEGOQLTLUBFCETMAGM9XHISYVSWRI9DNAILRHXASJR9JWTVKICGNJQAGUABIIUYJKJMUIBFRIAWTTICTDIXHOJBEKWKOBQKNPMNVDLAQFROLJHCPSH9IDVLLRZNKHTNIGXVUZAOYKGMKMRHV99LJEQGREDEYKYVPWLTDQMPFOWJQPBALNVUTTGOBID9NZIXKVRJOOZ9AJL9UBE9SSEEEIWRJNC9LGXRNXBVMXXSUBATQXKTBVDEDWWZEDJYRZLCLXQJDNDDFHFKOXYZLGNMKYULQQGCHMCPUDC9SLIEHEBSECNYNHPDZIGRMXDIB99OQTQJCTT9BRXVKOIV9PFJEHRRDSELECCECSEHMRUSO9YEARXFJIWNHCT9NPLRVPQXUVCQGQTHWYIVQP9WAFTJUWFHRWSTUIQXURUUXSKFE9LBUKGVQPNIXIPBJKVWJKIIS9LFFKTADGDLPXCMJFKCRAXSMZLVGRXBDNH9BDQXPPLVYHZQFPNFORFONR9ENQDJCDAWUDNGPUFKBBXCT9VGKPSFQTTQEJGVDMGJEFKPDEFKQOZD9D99LDWNYWLUOMNGXBUHZTCBRHYJKX9IYVLAQUNHJSFOZYFFXYJNXWQIPAZDSXXLUQXAUSDYGYQGNXZXXQDEYZJHJMYWJGFGMINQINECCFSWPCQY9BWUNSPZJWAYZSAMOBMTJAJDPQFYNCYYCNEAQLDRV9HEQRKXYDIWTNJPRJDKYPOOPZPKXLVUSRXLRSLVN9XRPYNDUVTEUDPNQWGHNLFIOPOXXTKITKBBZFHIWODAOKEFFDRYCIOYFN9LACLMZGGWSOBXRLLNL9ECOJ9ULZKCAYRWAYNZLGTSSORZHQVJEHLNKIXPWZNOIDNFLWYVICHWEDPEDSJVJGYGERMKDDERBGAWJGJCTSQSE9CWR9VSIGKPJXDGCWPV9XJITF9QXZQKYFXJEILSKZHPCYWLLYBGJH9UHXEEKNM9WEZMTZOAP9DYEQVDEMDJNCGZJZQVBNULRARFBJPY9UKGKINHYETWWYMUYWKFRQEBTVJDBPKYEUQAQF9MMXPQZTRHEPMZLHW9YPXRJY9CSUZJVCBRQWEPJFODKDSDQSTLTMVXAMKVENCZLOOYZWYUDQRYMBWHVN9KABTDWLNMIWJGMHPXVQ9OOQSWJSUZHNOPYKHRLDMQDNKSIWLUNZFQGQN9WAFTOBNDVXWBWCGFULYKALOTCEXUUYFSKYXVRVATBGZTFODZXVCRKBWVIVZXVOYCYPSAOBIRFFCENSYIDJUTLAJQOMVSVLDHATPFHOPLNMWOFNKQASTYUIPYRRDKMCRTLGDGNFZKMJCBFUHZHIIVUH9BQQ9AQQQNBPJKKSWQWZYFXVICTRCVUBVXUIEJHKAHRTTFWEQFHRSFCQJI9PZKVMQBGCGFOAQSU9CZVQKEXAIJF9ZIELDRZHCWOW99ELUMZEGGWJFPIAEOEJZQQBDRRWXYGEMGAEXXIRZ9CWREIKRVDMMKZHSELFOCTULYHUYN9SKTIY9I9NYSEGQWOAPQUVFQMCTFIUIZOCMECWJDYLERN9LQ9IYGF9W9JEEGXAEF9AYPJAKAYBLFYKTKFFKEHXWRYKYMJHAQDJBAMUBDHLCAGBHXHXLUNIKACDUNVU9DOJKY9NTOTIDSZTQPVYLJZPONKVOFLA9TCSTXUGE9DAVMSJEJWCWXZGLILZXKF9OXSZWNCSZJLIFIVJSMBHPDPYFIALOPCDXDHNYZWGNWOOCUTWSLSGFPHBV9GAUOYGXUQIFICVUONDJNPXLMKIOLKFUKAC9TNZKDPMYSXAMFDEFFEAEFTNFVKMVLEJIFFXOEGKCHJXDZLNKFJSGQMDCWQDTIRTZUOBZLMICFQGINEIWL9ZGSWTJBICINJWXDRTDDXJOBBNCWZGIZHVUNBWWIDMPXILXWESHPAVPPYQDDFXCCFJRASNECHLUHRJTROHHDXOEDGMNMYHCFTEYMUPZAAI9IA9VYTVJQCHDCNYFV9PKWRUMAUPVVNJKWGBPZVMLEOBAVNXVQIYWIGYOWDXCWZUPJZZBGWZMXITT9NOULJPZJQJGNUVAFZCAWKZOTOVTPZJ9GFAPOWICQEOPILTLPEZZZDAPBBGBJDEXXKHEFXXWXIBCLQTRRLZRJVDHIAJPFTZUKJMHTN9NYMXTIZGJSFJZXCC"
            ),
            (
                "W9ECPBPMON9LVAMZAK9LSIJKBRBFRW9QRPMSNDZXCHRNGCHDFZCZCVGRQYY9JNQCYFMYMXTWQVXRLHHDNPTKTSXLSAKVSEJQKBUKMSRRZIUMIZSRDXHRWHMFFYGHDPHXGYMAUKEGWODVHXSNKFDJZMDTCSPZCIP9PHTMC9MYWM9PEYTUWZKTRBIVCIDBFSEUSLGOYEHAGOPWLWBPFP9LJHAPWWJVFOMTMZPWDSNSPHYXKTCQEJ9UOQVFDIJDXJBFFBU9IPXEGYE9LJCLTSMZV9PBFRBWNMRUSTSOJAKHMHGVLUCSK9LHHXWPHHPJXHKXPUCSUJEPWAYJKADEQNA9CJMHP9DILAUBPHQECMYWVBAOCOCCTQIXPOPBJCEYCWGSIIKNIGNCLDDLYSBDXRUTQXMVPIJQFDTIU9JWQLAWVOKIJXPWC9XVYMHFSAETJHBUCBKNIY9HCTNCPL9TK9XEZIPIXQYYCOTMBCKNKZBMJYLNXTO9DWHEJGRFBASPOLHAKCBMIVQHSQFAGFQLNGFWWQGSKROAEIPZXGIYPEMCBLUWFBHAFHPDCDXJ9N9IKCXAZPBLAAYKBCRIWZITPNTVUVHOKUIEDEXBPEYZJWGJYTYWGHGQNLAPLXREDVGUI9F9KRVBXMYHZKWATYUIIMBSKEHHTUNUKCVNCARBTONHTVMJDQGWRIV9VQHIWCTYWHAVNCPXINGWYSMFJMJJMYOXGHVCBXSERMWUPRIVNSDTTGGKPY9AVZTIDNWIHUQ9CQRNOYJCOZDWQXWKSLAYGGTOU9IZYPGNIJZMAULCPKZHLOJKCKVTYGLPNJM9GJFPGWNUWUJSJ9PXTWGUHAHEYODNFJQMSY9O9XKHVKZOHYRZVUVERKYAFKTLJPNCK9CI9QLEZFFJXRVPFGVXAIGWT9KSXHNRKLNBGFFCPQSRQ9QJYQHQNRAPW9VDLUAKJLUBSLDJDFLGSKFQHUJDFFCWVQMVTARAYBXK9I9FVRYNJTQKZOCVAIGRWKTHXSWGLMJFNL9ZTRKNRJ9AUC9TR9QTHMMMJCIFRCAG9RCIMWIJKJJUWJQEWNT9VPUICKLEIGKUV9FHFPQYLJUBZZKEWMBFWNTOI9VHZUMIRVGCWTK99DFUMPUUZKIWYOARDWGNVODUXTKQKVYDPYSBWXVBYRAGUMFOAUSOVFT99EUCKESQEGQRMQNKCTD9LIUNSSBJODLLY9LBLKIIDEOITSJHJHXNRHTPGOSHKPVVJ9IXZFMPEWJZYZ9IIHQZHDFD9VW9FKLQBSMDRLGAVWFNYXOHANCJGAAYTK9MDROLJLO9P9SDZEAVHWXGQXCBDBHCSRNMVBHUODEORZEXMMHCIPHTKHOFVHASALJLKRMGT9NQWHVZGJCVAVNRLVITZVTE9NJS9PGVAWCDDISDVNPGIEHQLBFOUZUKWWVRPJMAAHTAGOFWGIVXOYTEVWWBZCPXUA9ROBRBCVWRLDONVZUDPSCQ9MB9QSRLYRHIOYVTFNWMRYEIZURTFETLYGGBOMSLYCOIXNQLKWKGRWCSJUGQJMOZIVYCCJZEGGXEDGAKHALJSXGXKGNPFFNDWSUB9UDNDVJLSWKSWKUBJVQFZSR9BKSPAMKYTGKWNCPSGBKMYGBEIHNGTYSHXEWYDKHMJTROXFMKYLMELPSRDOX9JI9TEOW9TMVRGYGV9OBSWGPBSAIXOA9HHXGYAIXAMNEBCJGJVOCEF9YCJSJCWGJYZNREIGM9MYAZ9XHAWXNUWBUWCFQVFFVKTYLIVJKBKUBMNDEAUPUTUPLXKUNYEVCPFAXWDILIKUEFLB9WUQKLRHDKVANQPWXNOUGZPUATJZTXVM9THBBVDXCFRHATHPKKYSVMVSJCZH9ZCKHQQGDTKXTTPCOZVHNKBGUVTULJZCMAKXHV9CMQN9P9XO9ZOPZJEANZRQZNOEFYSOKAZOFCCCESSNRFZBROBKPOBLVHYOBWKTCVWDEVR99HZRQDQTXKKFRYIPGH9TSASBEVSMXRDNH9BEJATDDNUWMDQSYTJU9SZKIFIWFTCACMFPDMYGJZWWOHVXBC9WQDWXJGXXRAAOBZEAGHKVQCSGARRLZIVROHCTTGGLWRDNUD9SQUNJZRNH9TOWTFCZGI9YCHITCHSTV9DYPULHOLLOTAUJGZSHFGOTFGHBMUEFSVNVXZVJ9PQMRGHHE",
                "UIHGKSJUKRYAQLAYDZZT9GMD9XCNWBOATLVAXVAMEPSIWCUDHZJVCFNUPHOSVIMWQCYTACJLEPZIYZAAWKTNSCETUHULUBSCSMSMVMEMOKBZ9TAHTHHM9GKYMJYZDKHOQLSYSBPHSCIZKVZZRE9IZWOS9KXZJP9VZDQEZTPLSXFAIIE9ARAWDRIYJOEBVK99UEJXMACJCGYIERGWSRDEUWLKYNHZSRKOR9SUWS9HD9KBSZMFZOAFQAWBHZA9RZWTWWTOSGDBJIPCGLLQVFANFUHCZMHKUNTTWRUSO9GGKPMACQQAYJCEEHIODHQXBTEPNBMBJUCB9BWUTIWIJPGWBTCKDTBZNWVYMYZRJHNZYLFCFBPANLIAQYPBBMWTBSSCWKRNZBS9AFVJUQRQRQIZDJVRXZWWMHOHNDKXAYEMPLHVVEDIEZDHLUOIMAUYQIVXXDTJTVEZTYTPMKGPODAHPEWZYJBRVU9EILJCE9GCEOKFEQYYQNOLENNWUQCBOVSILQWFQJMHXYNAKNTGJIEXOIQVRHLBVKCZPWZF9NMTCNGDWSHRAGLDPFYWXCLSMO9WBFBUMNCPOTMQCLRNBAZLUAUJEPQQFTKPGNIRTYKUCTQNDMNPKSGSFREEYOZVJMXTLTDNMHDCEXULRY9PORYTDELO9HQHEHIPILNQSDFIJUAIZBMCSPZHQANAMTNRDCPSCUXKYZHKMCKYOIQIHVO9LKKVXKG9TWOSKFCDVADLWUPQY9GSPCWGDJEWSEKIQXGGZNQGGFGR9NCLKTY9DLKZWCWIRVCGTOCNDYBRXEMKJZQKO9E9PTXXSWDUMPBNGNITUFSDANLUEL9YASFLGQRLPLJIQJVMLCVLRGUAVPUJYITCAK9ZVUCRENRKRKCVGBBYAIPQFAVYIXMBXP9NFJIHCCGAJODRIS9MNCWIAGAFRZPYJCAWRWUNULXMLECATY9LGBCJ9DXYSYKCZBEASMJJCCYIMWWIIKICARPJBYBKHJWIQGJOZGSYUHBO9IUUZKXUNKPNKCGBRQHJPQDFA9XLVVKUF9TL9AFEUYMIOPEFMKOSWFVDYYE9FOPJOGFJQJVBACOYNAUTSNKBHA9XHP9IBVANKWCBI9FEKESXFYCSFPLTPDHZQQEXINCGTYQPMPNMZGLDKUWXPPC9NGPAUINPCQXIRNILZRMTDQXPKEFFOKSJIQSDXLINZPH9TWMXEXXU9ZM9DOYRXCHULQN9RMNQGIUXHWKVNLHGYQCALHFDHUW9AGNNAHASEYPOOALAX9ZL9HVBKKFRYRRSUOUBKAXBNVKBGADNPGKIKYAPN9FMQQHKDROHNNAGAPNPEGJWABKHYJIOMFRBXZAZUZVFEOQDTBUVAIEJKIASDKHLIHUKDMBNQITMIZYUYXOWSAN9FUGSCWDFBAYTMLYCWYLDQVKPVMYPOKA9GWEHKQPONQFZZYYTR9JLQDVVPBBGRGKBZFMHFCXBDYEFMOTXEJT9WXIJBVJIIWYPJZVNOHGQAO9LEXATFMZWAAPWBZPQRZHOAYSHKECUTSWIRQOLQTFKNBMZPCNMVSIGNNOMPZPJXYCHOQUQXEWKPAZCHRDDQRPOPLAATYMKUTMFLPSYGIKLTCKBNIKVJGDLTDXCRESNFRAUTXUA9XKIG9WFGOPYGXEPETBENGSTYWYMUPPXKZJXBFU9FGEUQAFSXCACJXACZACJ9QZSYRFSJIJMBTLFGZDJYTDFKLDCZJVKCUQPSJRQLGMCXQFBOUNHDFYJMLFCDFNCBMVI9GPVQOOOJAJQXZGCKFCGQBLHAMPEBHUURHPOIVXLMYUBEVQWRUOTDZGKBLYFP9UMYDQZYWKVOGHDBDWHTHAAPIKLVSXZOYLSWAWOCO9SDSZDWQEXHHBOXDHDNOGHGQVS9JKLWAVRUSEFEIIBSHBKXC9CXRZRZADASNBGASTLTI9YSJWICCTVDRTESDHUNKPUHNXEIZKJJRBCNJRGA9VHXBWMAHUXCJTSMNICQJMKCUSWDAHIXLUZQDIITEWFCLFLEVOVQQRKZTSUGCDTEQPEONILDAIDTMKTTZ9FROJJUGXGBLVJ9PYC9WNH9RYABMXMRPGZRGCBHFKIC9YBVXMELNAOBGRFJMLEVOCXSLMYCCNKJQHPY9PDKZSBFOEUIXLOEIBHEEEOPGWPTNUVAGWZHVIVOMSZTZD"
            )
        ];

        for test in tests.iter() {
            kerl_generic_digest_into(test.0, test.1);
        }
    }

    #[test]
    fn kerl_input_6561_output_243() {
        let tests = [
            (
                "CIVIZMYHVFYZCXTXLDTPY9DMZKEEFMEABECNS9RHMIKQMHMUXSAQXLGLSYTRQCZWTQOGIQFFDWVBOCXXTVMRRCWQRVMCTBEIINDFFLXRIBJMBRQUCBAMDIDCAL9ICXFKOIBGJWKENILISRCZZU9WWPBTPQXOGYOFLWYISNYVHCOQQSKXBOOXESJQLZOHZAFRXOCGQRL9HUZFXYGUVRALGELOTEWNGYEZWCZRRITFYHDLWEZXPJOM9HSHMEUXJ9UCKDRYBZUIRWOSCNXAMGUTFUUPLTEYURVFROXZGGA9EFWROQMH9SZSXGNCIPXUDCCXS9UARJFJYDEEKNFSATRVNELTFXVX9UENWHXBQOMIBV9MUI99B9C9SSOFJYGBZCAHKHC9VIQRD9OHBQ9AEI9HRGQM9DDCJSPRQBBZRLGXJSKARRJTZWTHUVEUVPFVMUIAMDBRLOTKLMXSCPKQIULZ9TVKPRHXPFVAFQTDMOCHJ9DOFIYDWMKQXKLIZVXRRRSCGGJKOXOJH9RWYCLGLQR99STVPNGFOVZCJAJRNUCSWLZLXOEFHNDPHIMWXNENZZGYFFAQSXQPSZLBRSZR9OHIKBLMHQTOCLCQRQYEYGQEORKEXQN9LGZ9Q9QAEQOFTWADRSLZTOWK9SSDXOUJTIHYTHNYWRRJIHKPRLEK9FOSCMVVBAPBWDMBWIE9UAIJYDFPZEHSDIHOWTZGAHPLHULBFYJSACTIWJQUHTFESUFURCRLUURILTCOJ9JQVKTDA9RPMFVQH9HTIDGZPSRWTPUOQZUKQ9FVDFSCTQEEKTGGDXQUDVXKCJBMUCD9JTCYNNYTXDZYZEHQM9FYVGCCTJUARNKJUBL9EPLGRKYGBIDGVHUDGMDMHAAGNXQCXCRGTKL9NVNADJXIINSZVZNJVUOGISRECSUDFMNWBERUOSVSSZOLFYGOQTRMVJYQ9FDNOGSWSWYZHMRRGCVDKSLYSMKPLNLLVBQVPIVWVUQKSP9BCNVWJVSDUOBCSGPNRDQJTXPOVQSCFIKENKSG9AVFYFURXSZGYQZXPO9LMFDS9JQQUKUYXOANJAXJZWUUUSSWVZ9KJDZFXOSITHTQJYVRQXOCLLLSCUWN9DNFDGJ9ITECMYUJJPNK9IRBLRBDTSC9CVGFSKJPERC9BKRBLQLBXDEUNGCWBYYDYRWYR9TRCIQMOGNQGKWSZSCICTDUJHYOEYV9TNHLZWMDABDZCYHVMPLBAZXVFW9UKMFPHZ9ORQEFRFXXGOPTJBXEAFTBVRGATWOEZJRUWETAKLYOUHWZMTN9ABLMRLXHBSCVEWABNCYMOMMVDA9E9BWSNTVLZNJHPHC9JTJMQXZIQQLMBPPXTUXMYEVYLYERVWGQXSOO9LD9BRBDHQ9GMEKIIGCMSVXZFAHBZIM9ROGJGE9YTGSUGSIUYDNABCVZUHBJSKC9GW9SXK9CTKPKH9DFQJKMXWFKWD9IVNOONUEYPJTBNFEZPADBEIOLWZLSMXNEZSNFHEOXYJDMPQ9IKTEKCFSGVQDJYLRXHYMWFOWTB9EWDXKPGEMZWFLIDLZTAHIZ9IFHACVBXCXDZDJXLKYSDU9BMOST9HERRLKRV9UCKXFPSZSEBIZNYIDMQDFUSNTXNUJASXEXRHQMHOUWD9OACKQLSHVUMKCFMGDDUJIMCLDRWJCLX9WOGHXFXDMWUFPIXYWZIGZCXX9ZQ9XVTDWI9FRRKUGRUTSVVMGVPLAFOXGOGSMSNRURINKPTKYNNLHHYCWANODIPVCPMVYVLWFTOOVQECXNYYDVFZOMGAOQ9AARCXXIEELVCAQIMWLZNKAWH9AQMLCHGSKSRTTVGLK9MKFEMBNMHHDHCXWMJGEBKMIPRWYFMNJFBPGOKLSIFSTOCHX9ZKOMLXJBHZYRKLYWI9AQNCZGHCPOHJCNUETDXVELQQAGAEXPRQTJKZUARPKYFDUOZPPLAU9ZPJQMZOJYONLOPBFAKADDXBJTCGNMEYZMRINLBXHAK9PRWV9KPUVCMVUFLVOVTSQBYZ9LIJYQUFYJP9SZ9XMMTPH99CQMKTSSWOFJPDBRYMRZCOUHVXX9VJWLGUYXWUAFHBJZJHJWBDMRZYADWNVYJKQ9GOOMLRICCWXZJNDRSETOZWODRMKDYVXHNTTJBDQQSCGCQS9YLPRRWKSXYYORCOBCYUOTDMN",
                "BQGLZPUNVNISXVUWK9NQOOHY9CQKZNILIPVNGAWGKTKBJBTLYCFSNBSNZICOSOYRGYYMXYMLUNKGWG9W9"
            ),
            (
                "JIGHBTOHJYTSYGJX9DHSGDXTXIMJMBHOCG9FLESYXIG9GWIRTHWKERSNJSPCUSUMHOQJZ9EEEDILOYDWIEDPLSPOBLUYZNUXFPZZLQMQVZFL9OPPDFACDGHFVUUO9H9LRSNFRLPVIWEBMYA9DOYIVMYIHVZBZVAYNNGGNFONZAOFFGCUXVLLMEHSJRSWENOMSVTOCMJN9PFPNWWPEEGMCNIIMGWAEYBCVORKWEYSFGPRMCVDFBGRXULAKCW9YNLAMKWCRTWFDMOEHHQ9BRZEED9TAFEHXSPFCMMSTFKEGEHNLMHUYFUYFZRGJ9XHDVJXZZBZHTYJJCLIFXQ9GDSPHQBD99HCF9QLWCWCE9SGSXLVXJEPPFNCJWKUEJRLAZJHHTKJUJM99GMKOYFYPTBGICICNCMH9ARQRLDYMVIBLW9JKWCQKDTIONJDBHZTRJWHEVOU9UDVBFKUHHSPCCLPEOCIXRBZRLACDHBWMEPPWNBIJLVMUKCNDOLGSCNRQERDRWSBMKDOOHDVYHAMKLFIZLYONTGFYOWWJAMGXTSTIVMGNEONLLHYF9JHEGYMVADDYWMDIZLQAKS9ZNSYIVYZPSCPF9QBXAZZBWNSDHGFFMDG9WLE9JQPYMEVRGAFIHYBXZSGDSQII9D9ONFSDTTPQLKQGCDM9VSGMMJAUKQGVCNUBIDXAJIHEPJVZMTAOMXLYXXHB9WTYH9VTYEDPLTLMLUCKOPSWBTQUFLUJOFBJQP9LK9U9UYCWZVESLQPDOBAEJLTZ9GMKZSINTDYSYKXFDSPSCHAGGWGJOXFLADDDIMBVJFWOX9WXPLMLKNKALPZBPGBGDGEALKVXYHAULVUBNPLEHMATZPBCWBQRWY9VLNGTJOOZMXWWSVE99PDPBXCQFLOJYQFDCOAGTOH9NLWUHUQSBZNUBEGDCTYVPRUCIGGQUNCUQDCVOLKZOPVTQLFCUFBCLLQ9TSJLYLQNFIBPC9LJEWRIAVOUGFOGIQGQKSKUWUNZWJUHBH9BR9VGLFVDZRHJHADOXVPDCRCKDQSLRGNVSUJ9AAZETJSLLDYITPCIUBGEXRNIV9LKKX9ZTRPLYLQBIYIFTMVOPHKKJLDPOBCNJDDLVIACGAGCTFJL9WUWDSILEOE9ITCJLLDOQJCLXFDOEMJQKYRAELHLPVMVUNUGQKMGDUHCZLRKOCDYJIOAKOXHQOEBUKJBVTWPZBCDYQWQBVFGLBRYMKVNRFJHNYFSVZGF9PXKNLBONCMKUIXGKIN9JEK9WDKIXIULOWBRLEWWOCKSBFUX9YVWIMXLNZXHIDLFXUEKKNYSKMGGVKFCEVCYKJVYWEMMBVEZQOGIVEPRGQXMQRP9VEYIWWGTFKYRRSXQ9OB9OEJKIMMPAGKCJZEPXELRRBN9VPPWCWWEIULKZRJILEFRNFWFXAZJIBMDECYLMQCRHKBFSQBDDKCGAA9ZMRMMHAAAWAYBKTEAEFGHWPLHATOAKCMTGWFJDBYFLNACSOYWRSGIM9VGGBGRLAMXTVQHSUYUSYRBBKYIJSBUM9RNVYKTIXE9FIFPYSZ9GHVMQMJZFFVKUMWUEISBVLCGLASIIYDHHZBZWFEMGWTMN99BWCVVVXYQFISUUB9VRRFLDTZTYYQHZAKOMTEHHKAUZMYW9DKUXBZXRJXXYZOZ9ASDEWTRHXAQI9LJYSVP9NSFQENUUGDZIMZUBCZMYUVFNOZAQUMDZETBPWFKSCZTYHVVSJGDRHMZKIASOYVJGLNOMCUIEGKCZFJEEQPTSJFMBZGXQUAX9XHJRQG9CBR9J9MGMLUSDXEOMFKWYEXFGBDPXXEPE9PS9HBDLUMXVC9ORPYKCAUXQNZKIQJF9LOWALCSSIVPCGTUIQXHXJUVATRDZOSPSEUMNSKNECANWSYTYPNCGWNDPWBPSONPGUKQUOCYHQKQEEYW9CUQXBTAUBSFKPBKMVWIUHTTOPTPWPFOJHVQKQCIJMMMGXEXGACSWDRLKFHTENNBECZQXZPFZXHOWITD9U9RPFESNUOO9YQLUNVE9KMNDGVPHCQMMVU9EINF9UGEPMIKGSRVBEHBPKMTJETUVIAUIDLPZJNCZZZCQTBOOBTHAGUNESLMLGPUDNUHWSYXRDTGNVRCCPDPQWYZUUEHTKHELGDKKIT9IR9ZDSNNAGQJZLZTSIRIPSQYUTXMRC",
                "ZMCLCLTJGNROLPYCCLXTYHBWSENAPWZNXOXRFOVKMMTMKUGBVTCNITZHAPSXDMYYORFJHSGEFABNWG9RW"
            ),
            (
                "LDKRQAZHPFWGLHNC9CYXDAF9XIA9OVFPNTENKYNXIFHBYTMFF9DLCVZHQRYSDIATYYPNRRICX9WOKZRQHKOZVWZMXYHWKLKYNUCCMVCULMMRZIMPFVMPTNITZVAKMWKJHPNIQNTBLDSITDKLC9FILJBMVFRTIKWIYMTLDSEVELRQZQZZVE9QEMDDABCQGYQ99PSJBTCHHR9ZXATVVELBDVBCUDMGFMTTEXZJQMGOCBWTGTJAAFGLKERNBYWHCCLWEWDCXPLTIFBWGUL9JPHPYWFBDBAHMODAFFAVNDMEFPLJNCTCTNRPSTVXVVKWGFNGMYCTXXTOONZEAQBAWOLVILBCWKAFFSOFFDZYAWKZACUNKZHZZTYNNDIRYTMJJFZIFIO9JJRFWYTDEEHMSVPBBYCVPISTNUFCWDPFQJREURJLWJRQFNULLEZRBSAMRSJMDTUTK9JPBGZWNZDP9NLWHOTTOHRZAV9LONZSNOZBT9UFP9JWAQILJKAHCPWJXZCIIBYLQYAKLZYJGUZNXAZDMAIROJ9YSWRNBRPQ9SXJUGMGSDSWTVWWHTMUBRLCWXSOJIELFXFPP9TRZBOYFDZXNBWLBNSDFOFEXOLVGWFUXFHRKMPBGQMCWEEVZMFHU9KVKCYRXN9XHUOOHGEQOJJGYGY9NZLWOAILMHSOUQTLCUEWLRNVCJMELXUJJKTBGMBGZTFBXBTCHZJEUQCVOKSDGFOGRH9UXSRXJKBYLWYKTUPIWFVBFGWSRDOCJNWCNRQXEZMLHHY9BJPYARTLEEAFXGSEEWZBDYTGCPQBNY9VDPDUT9VY9SIQRVQRBKDKVGZH9NJYGDFAV9EUDCCU9VIDCZQLER9ICESYGMXQPRKPLLEHARNQKIRMR9XNORMSDCLNFSIJMIIGZSARPRPIBHHE9IHVDNADFWJRTZKTCFQRTFJXANDQWBFVGWPMAMRUKWOBQQEY9RMFPPRFMFFLKIBZNWLKBHUNPMEISFQJIRIDRSFZMOLPJNB9AZ9EQFUQQCYSMVATQCLILTTDHBISW9UILDWUGLUNBIUZHMPC9NUXRLNBAKQKYLHYXGXKU9CIRFZ9ISEGGBOOIIGTIBOR9UAX9MV9VC9JSORWZGFSXRMEFEHSLKZNZNCBNHRJZBZNDRAEIKHQZEUS9HAYIIWISOGPQLKKTABEG9DBBHLYGUB9CWDTYDKXEPCEGSPNAETB9JOCPHRJZAOVUJLIJOJHYYOWXWGSVUNQZZIYHMSVYBVIMTPLMMCVIYYNRTKYGQLOUGVWGGDQTSVDARALLSSWJUXQH9GESKLCNIRXMIGTUUTDPBELUUNGSCXEXBOFVTCJBFEQADIDPLVFVZVMDULSNTUWSUCLEXIDBTYUBVFRZLOOKWDLCNTUHGDTWYIGMUGKCYZKBFGDVNKTNYIN9OSTVQDCGKTBLTNERURBCMACVRSJZW9YAFTWXIOGNZAQHOJTOBGZNNZSGFNQFPIFQJRTCKUZDMPZRPOORDKYEZHTMREQIPQIHRC9RIEIVPCHJNAAJPIMYZZF9XNMKVCHR9IBUBKTAWQFSLWQZMPTVOBVGRSRBLDZO9ZGTKLQYVNMHOEWQJFDIPTDNEANL9OJAHMJIHVLCCXQZJRRTKCDZMTXWD9IFCSTFNEDKKNJAWCFEN9LU9ELUTXCQFLBHWLIHNPEOKCONQWGBXNIGWRARUSZGATOSR9EKMDMQEPNRWOLSHXBAVUNZVRQDCX9ONETNFWEXGFJGHBHSXHKFOQWNENERDLIZM9UZPQTLY9GEZBUKSOCRPTCZYZRBIMOCZFCGYBQLNXYVG99OLDXHCUUXLOTWYZSICIRGF99999XHULVOCTGWAVSFZNJRCCFSVTHBYFLTXBTFZUGBSFBEUZCIZVCZHMIKCTOCSTYNECJEOFQHXBALDAESMVZWKKRQGYVIYXPWPYTRIYFQWGTRINFCNYYZLGA9WCUWJZEHGQS9TEOSOGCTTNRYEUX9VEQCZKIRXUBNLPJWOJXUYWSDSKQPOZFRLQOFQDYORZOXJIVHRZZHDILQNCFJF99XIOMEJUMYUBKAY9IMVYQPTJPCYUULYYPMDNHVKPNTVA9JGBLJMXLSEOTPISFCHCSPACNJQRXJXONEFTEDHZOPBP9BBNOONXBGGMQNTJYVD9ALWHYWTKBTGTYKHUGHJ9PPELKTIK",
                "JZPY9NZBOOFV9VUQWVMNNAJKMZWLIJBYCZP9NZEIGAMABBHMEQHSMIKJVKOWXES9MAYEMOXEEYJIPKLYW"
            ),
            (
                "PINSICEGKCWYOSNIEWJZDA9VRRHPVFMSZEUBZJQYK9JS9VPFTZQOGWPRVLSWLYALUSGKBEQQECANNWSBBYGPDILJKBV9JOZMSCMFSSOFXNUQXUJPQLEKYUEVUEGCIZXPYGTB9GHYNMEJDOSZGGZPGQESNNJU9PEWIXQBJKLBUSNRKJZLWC9FSZAOCETTYDYTDXDSYNJYUALJSMJ9VZR9AQIELALGNBDHNBFNIQFARCZBJDA9UQYVLAHLKAKKREXDONJSUIOEXEZYEQLYPVXFPUQDYZNOGLVLD9PONRXGIPLWJVOUSBCLKJCYQYSJOIPEBZWWIZCJPQPGGYJUQVABSFDILWPYACDHTOAVBYENHTINM9MLTDV9KCYNFJIIEEOLLXCDYTLZQOXTIKFSWMTFVZWHDPYO9TUZRQRNVUHQPQCJECEGSIPNPRHRLC9NYQ9ZUOWZV9HBLCFSBVCH9ZJOMFBKW9ARQRTUSQQF9UWUBAGRFXTG9WAXVOKUSST9SNIDSJQNFCWIKLTMCQTURZNICDKKIPYJDMSVFZEBOVKOEMCOHPFHWHYPNI9QGNMGPDPUUODZUPEALPAOEUBTSPTHIVSCYPYKAE9HOMSOHYJVIGVZVYY9CWBOSTQLAEP9UPINWIKSVFZHAYGXRBUDAEWJATLEVNNLMPSKOANBJNGANLHKZSWEMVVEJSOSNRJFIKILOQWNFPLQRCJVZXETNTDSMYPAPH9TPGIQKOQ9GJUXDEZIULINJSDROYTYMBXHADCWHJE9LAX9YOUDDSJPPLFR9MQWFXKE9TJFMLYPMLTFYCKT9FHICS9ZPNXNSGGXJZRGLNPSZC9IWTJQSB9PHZMBJBJTGBYRHTNNSOESFKTDQFQPQNNRDAR9SRJXD9YTASZEBXEC9GLAFNDLIXLI9PEIY9HSWWHOPCIBVETTICZ9ZGKIYHRTUL9HZUUAOO9EBTCSUZNWFJLMXFKXPVBLVWJAKCOVPZJMKA9YGARA9GRAFAZJHTCKMXHTBTNOWFYVMHRRDJGLXDOOMUAQVZJTX9RUBDQBAYOMP9FZAEWRSJCMRFQSWSIEFBXMUJKCVDBBKQFFKTSWQLEEXEKNNBUWJETJPIUTFS9DDKAXON9GTTIRP9Y9CCOVFTF9JYGVFQDKGDMHQVWJYMVIFNUPABDVDOMSWKUFIXKGELGXRKVCWWELHACQOVDXTGGQBCKDWU99TITSZOTLSD9XQFBSWC9CUEHTVFW9VHGXQMQJOHJERNCIPBZUFBESSODWQOMRB9UVBTKASWYVRJG9I9EWUDFIOWPGSWYKTJEFGIARRMIQQZGXGIUWYUDSRSPKZE9D9VBLKZNBOJAKXBXSORFRNSIRXCHPUWGJJJH9JY9AIXYLSSY9T9DYJVMGJQVOIGE9GJURRDUUSWXTE9EBZRT9PUAKWQFFOBIJQHDLMDCNAMRWHQOFYDWMTGNF9ETWYMXEQOKJASOZHQRPDDYKVVVTGMMQGQ9FTKXYPRWYBUDGFZKWDHIBOOTXCIVUERLTVRZAFEONTXLGEURHSNYMKLGLDVIEMYNNRCKRJVAD9GVVGEUQMTWSPXYUAZXELO9GGZNTKQSR9JROBPIKIPIWFKKTNNZWGZLSZWGOTGCYRIZC9HLALGQRMBPRWWDIAGAYDXWWAFISSNAUTDQORXKFOARNMFX9VQAQLEFPSBAFEIRKXVERUVRKJLRLYCCFMPRQTMPQNYNW9LJHYMIVZKEIUU9WAQMIHZ9VNTMSNBTRYATNTIZLC9DTCEORO9MSXQXOZJKSYXCJZMJBNHP9FJQHV9MBBMNEMIVJBNCBCNKSNTAXOETBIPRMIVKZDEZVWGBHLDVAGHSOLZUXANMYTMQLJALAFXBQUQDGLSPOJ9RQGNOXJBYKTG9XTQNNIZFWNFJIQADVIRMWBODHRIYLARPIQTBXYMOPZU9QLAMNGUCXBUHWNNBDFDDOUAUTPKOYUNBTEDSLFCAASQUMEYWQDQGUWAMSS9XHI9BLCODEEKPHHJLAGWJBAEL9QJYHQGNMKKAFEQXFZBQXYEKWHCMUHNHSBVFCCJQKXYLN9LD9CBZCXPCRSKJNKGZSHFZTIHNBIU9JMYMMWZNPHUTVICMCWDQBVRGQNYNTHOGPJXAZRLMPSXBONOZHMBRQHZEEAXKGKYVOZLJCFCUPSEDLELQMXXPCZNZ",
                "CUVOLENGLSCEFWMZRI99EJASHPXGKBCATXBRFOEKYXJEWNXNC9QWMBUNRKQDLRISGFBEKJTXJDTQKJSLW"
            ),
            (
                "ANPXL9GPCQUZJUICKQWAHSKKWSTPHLXZTFXKVEUVCLIQ9AKOVWKNEQLRGQGSRTZHUNSFBNQWVWQGAGTFHJGFNGFJUWKCMXRFYAICXKKK99EGPCQT99UPJTCWDBNBY9YOOIAVYWZXGNVKERTILEZIKT9WGPQUPVWUZYCFBCSJVZKLITY9BLWCOEBFPMQVRJWKUFNE9YBHCMMQOHBGTSUDAFNGSNVUBWMUQKPUGEBPAHOWTEFX9XKMCVNHAKSAAVCZLCVTZDGDXNEUVYOVDUBALFNEPX9HKOOWLMSMJOKLPXYYSJZCTGUITZKRXZFOTINPOTYVAVHVZZZJJSMBZCOFZXTDHDISCMQE9DMMHSXNVBDLPVFKPPZ9BU99VFDUFSX9RFIWTBRGWTVQDBYKNVVPQYEEVRL9CSCAYIDFSZAIIMLZSRJMKCVQMEYZTRJBEWRRZLTGCSNZQJ9PYSECLAEKKIIMCRCHVJHYCRUNKQXXZJGRSERSXPLBXKDYEAVOJZOKNEWJWOULEIQOYMZHZTDDZZIP9F9EPJVCKTFN9U9BDBHNQ9KCPKWJQIRDETZDLUTFAEJAALGQMMNASIFKZHR9ZEWJHMUBWV9RD9NGHBLBHUKRTAHAZ9XZYOYBQGKNYQELNZEJNRXKMOMYBTREIGZJXBAJYOXOZQMROQQQOZ999ZELTYF9YMP9ZMUAOXXLZTUES9BH9ZQDWYKOVBAIDSPDMHSKBCLSQKSMEOTSCEM9GAYDOBAAQQHZEIZTDSLSUXNLFXCIME9EMXJBBJJXXDHAADNFNBFVHEUSPGDCDRPGXZGJBOCGGZVQFPCJHEWL9RPHIQ9VCQYBDQHKVYWYZJNUIMILDKCLIXJQ9KBJANULYTXHOPDJHHEAF9LJFGVCYOLBTJBOGEDLUUWBSCUBKYIJRZSKEUWHFXKZCECVTFHZHTKK9KRESLWYWDHFFNZPNICDZSDSKJJLYUV9KSCFZVKODRAFOJSQTHSDXBWDQOUDDG9AUKYYUXK9MXURRUNBPTFIRFOZDOKYJTSDUNUKARRRHKNHKOZPAIGSZTC9HPQYXWBSRREYZRONJVEJIXTUP9NDBR9YTDFXKGTHXDPOBBPRIK9YHGKTI9HPJE9Y9LYHCKRSPFGDJVDRNHVPCKAPCGERSBI9RDLGZOJSLAVOWLD9UDQZAVYMMEOSWKAHLWFMZMMYYQVSSZIJFXONGMZRBCNKWMIYYA9QCDDPGTWGQZXBEUJIACDBWWTH9GGGWIB9DCJZVYBIB9XEWGVQKHNYIEZBRQIWB9JRBEEVVUVXZULKFGABHUC9UPXLKJWHJXONGFFDBMCYYTAZWEELOTGXMFGETMFJLMFVBGJVXAKEKSRSWRYIBQCPJXRGOXTHRBVWNYVKVOW9SWBLGCPRAXFVBPKPTNJDGPWWVCHQQORCEDLIFOPFJVFORAYM9JXBNHNOGSCWPXOVGF99KTN9NEPISMPMAXMZTRBLUQAYUSRPLIDUAQK9IUBGQUMYDGCMFYXBM9TWWYDIJVFYK9PJLZKFVBAWHBLVHQAYDTQTXSCFMMEIPMQ9VTFRDGQDDKFYAVYTIKLDGFTWEMFLP9PKSCULZARTKN99DIHCM9ZKTWLJIMOERNAPGMQLSWEDHOOTEANJP9SMYOUXMUHMO9QBOXLZZXRCPESUSV9HXBUJMZ9ILNCLHMKCCRYLNHWXHPRNJRQMEHMTYWAPHFLUXDAYTMWEOBECFQRJRAOJVABSUUPJUJBLIDCOQUNUFCUPOHVMNXGXXFOMWEORXBRLSHRBCKYARZZSJPZXRMWODUUTDSAGNKZ9FROMQSTINHYVNEYNKYD9T9CROKSTKUWJTIEDMBIATIBVCGNRLDUIWUOBFQU9VVBOHMKYXLGPNSSIGSRRNMXYARTFKUP9SYFIEUGSMHRG9GAJMTXXWFULL9QKVFKZKJAJJLTXCLNWIX9UKJBONETTUTIORBGYFDCSUQHPOXVOKEL9H9GVHCTZGCAOY9POZC9W9LPJGQ9HSXMTYONJW9VZGBRYUZXGMIKEUYTHSNCMGJJEVYHWFPJ9DEZUWQQNBJUHQECUMXWBTEGJWPJARHIHLXGCNYTAIESQF9ELGDDOKBOE9IJWUWGGRJKSG9JMLNUOVNREKBOFUEDALFMZ9VKCLUEEDXOJXMRPZDOQ9ESMQXSNIAKPCHACJRY",
                "DAEGYEPGLTOSORGOQNNRHPHARMUWKOZBUOCVPWXIDMIQSMAXXTZYFVXVTIBKCOUXNDIUJWSUSJDXWCZOW"
            ),
        ];

        for test in tests.iter() {
            kerl_generic_digest_into(test.0, test.1);
        }
    }

    #[test]
    fn kerl_negative_byte_input() {
        kerl_generic_digest(
            "DJ9WGAKRZOMH9KVRCHGCDCREXZVDKY9FXAXVSLELYADXHQCQQSMQYAEEBTEIWTQDUZIOFSFLBQQA9RUPX",
            "XRZCRWFXU9UYRKFQRKWROIRGEVGTUGUBKDYGPWDTUXXOFVXWRTQBRRGGUSIEMPAISTUEYEZJXXEPUTY9D",
        );
    }
}
