logLevel  = "info"

[network]
[network.server]
type  = "TCP"
host  = "localhost"
port  = 1337

[peering]
[peering.static]
peers = [ "tcp://[::1]:15600" ]

[protocol]
mwm = 14
[protocol.workers]
milestoneRequestSendWorkerBound     = 1000
transactionBroadcastSendWorkerBound = 1000
transactionRequestSendWorkerBound   = 1000
heartbeatSendWorkerBound            = 1000
milestoneValidatorWorkerBound       = 1000
milestoneSolidifierWorkerBound      = 1000
transactionWorkerBound              = 1000
transactionWorkerCache              = 10000
transactionResponderWorkerBound     = 1000
milestoneResponderWorkerBound       = 1000
transactionRequesterWorkerBound     = 1000
milestoneRequesterWorkerBound       = 1000
receiverWorkerBound                 = 1000
broadcasterWorkerBound              = 1000
[protocol.coordinator]
depth         = 24
publicKey     = "EQSAUZXULTTYZCLNJNTXQTQHOMOFZERHTCGTXOLTVAHKSA9OGAZDEKECURBRIXIJWNPFCQIOVFVVXJVD9"
securityLevel = 2
spongeType    = "kerl"

[snapshot]
stateFilePath = "./data/mainnet.snapshot.state"
metaFilePath  = "./data/mainnet.snapshot.meta"
