# Duplicate this file to conf.toml to use it

logLevel  = "info"

[network]
[network.server]
type  = "TCP"
host  = "localhost"
port  = 15600

[peering]
[peering.static]
limit     = 5
peers     = [ "tcp://[::1]:15600" ]

[protocol]
mwm = 14
[protocol.coordinator]
depth         = 24
publicKey     = "EQSAUZXULTTYZCLNJNTXQTQHOMOFZERHTCGTXOLTVAHKSA9OGAZDEKECURBRIXIJWNPFCQIOVFVVXJVD9"
securityLevel = 2
spongeType    = "kerl"

[snapshot]
stateFilePath = "./data/mainnet.snapshot.state"
metaFilePath  = "./data/mainnet.snapshot.meta"
