# Duplicate this file to conf.toml to use it

logLevel  = "info"

[network]
binding_addr  = "0.0.0.0"
binding_port  = 1337

[peering]
[peering.static]
limit     = 5
peers     = [ "tcp://[::1]:15600" ]

[protocol]
mwm = 14

[protocol.coordinator]
depth         = 24
publicKey     = "EQSAUZXULTTYZCLNJNTXQTQHOMOFZERHTCGTXOLTVAHKSA9OGAZDEKECURBRIXIJWNPFCQIOVFVVXJVD9"
securityLevel = 2
spongeType    = "kerl"

[protocol.workers]

[snapshot]
metaFilePath  = "./data/mainnet.snapshot.meta"
stateFilePath = "./data/mainnet.snapshot.state"
